#pragma once
// Loc.h — Centralized localization string table for DUWN Mirror UI.
// All user-visible strings go through loc::Get(). No raw string literals in UI renderers.
//
// Usage:
//   #include "Loc.h"
//   DrawText(loc::Get(loc::S::Nav_Mirror)); // returns L"Mirror" or L"Màn hình"
//
// Language switch at runtime (triggers full UI redraw):
//   loc::SetLang(loc::Lang::Vi);

#include <windows.h>

namespace duwn::ui::loc {

enum class Lang {
    System, // resolved at runtime via GetUserDefaultUILanguage()
    En,     // English (en-US)
    Vi,     // Tiếng Việt (vi-VN)
};

// String identifiers — one per user-visible UI string.
enum class S {
    // Navigation tabs
    Nav_Mirror,
    Nav_Performance,
    Nav_Video,
    Nav_Settings,
    Nav_About,

    // Settings sub-tabs
    Settings_General,
    Settings_Output,
    Settings_Network,
    Settings_Audio,
    Settings_Privacy,
    Settings_Advanced,

    // Header
    Header_Subtitle,
    Header_AboutTooltip,

    // Status bar & Session state
    Status_Idle,
    Status_Ready,
    Status_Connecting,
    Status_Connected,
    Status_Streaming,
    Status_Paused,
    Status_Reconnecting,
    Status_Disconnecting,
    Status_Disconnected,
    Status_Error,
    Status_StartingAirPlay,
    Status_AirPlayRuntimeError,
    Status_Dot_Streaming,
    Status_Dot_Connected,
    Status_Dot_Paused,
    Status_Dot_Connecting,
    Status_Dot_Disconnecting,
    Status_Dot_Error,
    Status_Dot_Ready,
    Status_Dot_Idle,
    Status_PausedStaticScreen,
    Status_AirPlayStreamActive,
    Status_WaitingAirPlayConn,
    Status_EngineReadyPorts,

    // Sidebar
    Sidebar_ZeroCopyTitle,
    Sidebar_ZeroCopyDesc,

    // Mirror / Device Preview Page
    Mirror_NoStream,
    Mirror_WaitingAirPlay,
    Mirror_DeviceName,
    Mirror_Resolution,
    Mirror_FrameRate,
    Mirror_ConnectedTo,
    Mirror_ActiveStream,
    Mirror_StreamStatus,
    Mirror_RealtimeBroadcast,
    Mirror_ReadyForSender,
    Mirror_AppleDevice,
    Mirror_NoDeviceConnected,
    Mirror_HardwareD3D11Note,
    Mirror_Metric_Resolution,
    Mirror_Metric_FrameRate,
    Mirror_Metric_AudioEngine,
    Mirror_Metric_SessionUptime,
    Mirror_Metric_FrameDrops,
    Mirror_Metric_PipelineLag,
    Mirror_Static,
    Mirror_OutputOpenObsActive,
    Mirror_OpenOutputForObs,
    Mirror_ZeroCopyPresenting,
    Mirror_CleanHwndDesc,
    Mirror_DirectCaptureActive,
    Mirror_LaunchOutputWindow,
    Mirror_ConnectedToDevice,
    Mirror_WaitingAirPlayHeader,
    Mirror_WaitingAirPlaySub,
    Mirror_ZeroCopyD3D11,
    Mirror_WasapiAudioClock,
    Mirror_DxgiFlipDiscard,
    Mirror_Guide_Step1,
    Mirror_Guide_Step2,
    Mirror_Guide_Step3,
    Mirror_EngineNote,
    Mirror_Empty_Wireless_Title,
    Mirror_Empty_Wireless_Desc,
    Mirror_Empty_Wired_NoCable,
    Mirror_Empty_Wired_Preparing,
    Mirror_Empty_Wired_Ready,
    Mirror_Waiting_Video,
    Mirror_WindowsTitle,
    Mirror_Btn_ShowPreview,
    Mirror_Btn_HidePreview,
    Mirror_Btn_ShowOutput,
    Mirror_Btn_HideOutput,
    Mirror_Btn_FullscreenPreview,
    Mirror_Toggle_AlwaysOnTop,

    // Right Stack
    Right_DeviceConnection,
    Right_LocalRtpStream,
    Right_Btn_Apply,
    Right_Btn_Eject,
    Right_Btn_Refresh,
    Right_Signal,
    Right_RealtimeTelemetry,
    Right_Tile_Decoder,
    Right_Tile_RenderFps,
    Right_Tile_QueuePacing,
    Right_Tile_AvLag,
    Right_FramesPlural,
    Right_FrameSingular,
    Right_OutputControls,
    Right_OutputWindowActive,
    Right_ShowOutputWindow,
    Right_Btn_Full,
    Right_Btn_Aspect,
    Right_Btn_Pin,
    Right_Btn_Unmute,
    Right_Btn_Mute,
    Right_CreatorTipsHeader,
    Right_CreatorTipsDesc,

    // Performance page labels & diagnostics
    Perf_Title,
    Perf_SourceFps,
    Perf_DecodedFps,
    Perf_PresentedFps,
    Perf_EncoderFps,
    Perf_SourceRes,
    Perf_CaptureCanvas,
    Perf_PreviewWindow,
    Perf_AudioBuffer,
    Perf_Underruns,
    Perf_Uptime,
    Perf_DiagnosticsTitle,
    Perf_DiagnosticsSub,
    Perf_FlushPipeline,
    Perf_VideoDecodeRender,
    Perf_Lbl_RequestedInput,
    Perf_Lbl_ActualSource,
    Perf_Lbl_SourceFps,
    Perf_Lbl_DecodedPresented,
    Perf_Lbl_Decoder,
    Perf_Lbl_QueueDrops,
    Perf_PresDxgiClock,
    Perf_Lbl_Source,
    Perf_Lbl_CaptureCanvas,
    Perf_Lbl_PreviewWindow,
    Perf_Lbl_RendererSurface,
    Perf_Lbl_ScalerLatency,
    Perf_AudioWasapiClock,
    Perf_Lbl_AudioStatus,
    Perf_Lbl_EngineFormat,
    Perf_Lbl_AudioClock,
    Perf_Lbl_AudioMuteState,
    Perf_Lbl_RealUnderruns,
    Perf_Active,
    Perf_MutedSilentBuffer,
    Perf_UnmutedPlaying,
    Perf_TransportIpc,
    Perf_Lbl_Protocol,
    Perf_Lbl_TransportMode,
    Perf_Lbl_SidecarStatus,
    Perf_Lbl_VideoRtpPackets,
    Perf_Lbl_AudioRtpPackets,
    Perf_MissingError,
    Perf_ResolutionWarning,

    // Video / Output Page & Color
    Video_Title,
    Video_Subtitle,
    Video_QuickSetup,
    Video_AirPlayInput,
    Video_ReceiverQuality,
    Video_Requested,
    Video_ActualSource,
    Video_Quality_DeliveredAsRequested,
    Video_Quality_SourceLimited,
    Video_Quality_PartiallyDelivered,
    Video_PendingReconnect,
    Video_SidecarActive,
    Video_Output,
    Video_AutoMatchSource,
    Video_AspectFitBars,
    Video_AspectFillCrop,
    Video_AspectStretch,
    Video_AspectAuto,
    Video_CanvasMatchDesc,
    Video_Rendering,
    Video_RendererMode,
    Video_Resolved,
    Video_ZeroCopyActive,
    Video_ZeroCopyDisabled,
    Video_Color,
    Video_Live,
    Video_ResetToZeroTooltip,
    Video_ResetTooltip,
    Video_FilterNotSupported,
    Video_AdvColorOverview,
    Video_Collapse,
    Video_Expand,
    Video_ActiveCanvas,
    Video_AspectBehavior,
    Video_ColorPipeline,
    Video_Fixed,
    Video_AutoFollowsStream,
    Video_AutoRange,
    Video_AutoMatrix,

    // Dropdowns & Options
    Opt_Profile_Auto,
    Opt_Profile_Auto_Desc,
    Opt_Profile_HighQuality,
    Opt_Profile_HighQuality_Desc,
    Opt_Profile_Balanced,
    Opt_Profile_Balanced_Desc,
    Opt_Profile_LowSpec,
    Opt_Profile_LowSpec_Desc,
    Opt_Profile_Custom,
    Opt_Profile_Custom_Desc,

    Opt_Rec_Auto,
    Opt_Rec_Auto_Desc,
    Opt_Rec_720p30,
    Opt_Rec_720p30_Desc,
    Opt_Rec_720p60,
    Opt_Rec_720p60_Desc,
    Opt_Rec_1080p30,
    Opt_Rec_1080p30_Desc,
    Opt_Rec_1080p60,
    Opt_Rec_1080p60_Desc,
    Opt_Rec_1440p60,
    Opt_Rec_1440p60_Desc,
    Opt_Rec_Original60,
    Opt_Rec_Original60_Desc,

    Opt_Out_Auto,
    Opt_Out_Auto_Desc,
    Opt_Out_HD,
    Opt_Out_HD_Desc,
    Opt_Out_FullHD,
    Opt_Out_FullHD_Desc,
    Opt_Out_2K,
    Opt_Out_2K_Desc,
    Opt_Out_4K,
    Opt_Out_4K_Desc,
    Opt_Out_Original,
    Opt_Out_Original_Desc,
    Opt_Out_Custom,
    Opt_Out_Custom_Desc,

    // Capture Canvas
    Opt_Canvas_FollowSource,
    Opt_Canvas_FollowSource_Desc,
    Opt_Canvas_16_9_HD,
    Opt_Canvas_16_9_HD_Desc,
    Opt_Canvas_16_9_FullHD,
    Opt_Canvas_16_9_FullHD_Desc,
    Opt_Canvas_16_9_2K,
    Opt_Canvas_16_9_2K_Desc,
    Opt_Canvas_Custom,
    Opt_Canvas_Custom_Desc,

    Opt_Aspect_Preserve,
    Opt_Aspect_Preserve_Desc,
    Opt_Aspect_Auto,
    Opt_Aspect_Auto_Desc,
    Opt_Aspect_Fit,
    Opt_Aspect_Fit_Desc,
    Opt_Aspect_Fill,
    Opt_Aspect_Fill_Desc,
    Opt_Aspect_Stretch,
    Opt_Aspect_Stretch_Desc,

    Opt_Scale_Auto,
    Opt_Scale_Auto_Desc,
    Opt_Scale_Fast,
    Opt_Scale_Fast_Desc,
    Opt_Scale_Sharp,
    Opt_Scale_Sharp_Desc,
    Opt_Scale_HighQuality,
    Opt_Scale_HighQuality_Desc,

    Opt_Pixel_Auto,
    Opt_Pixel_Auto_Desc,
    Opt_Pixel_On,
    Opt_Pixel_On_Desc,
    Opt_Pixel_Off,
    Opt_Pixel_Off_Desc,

    Opt_Rnd_Auto,
    Opt_Rnd_Auto_Desc,
    Opt_Rnd_D3D11,
    Opt_Rnd_D3D11_Desc,
    Opt_Rnd_Compat,
    Opt_Rnd_Compat_Desc,
    Opt_Rnd_Warp,
    Opt_Rnd_Warp_Desc,

    Opt_Color_Neutral,
    Opt_Color_Neutral_Desc,
    Opt_Color_Vivid,
    Opt_Color_Vivid_Desc,
    Opt_Color_Soft,
    Opt_Color_Soft_Desc,
    Opt_Color_Custom,
    Opt_Color_Custom_Desc,

    Opt_Range_Auto,
    Opt_Range_Auto_Desc,
    Opt_Range_Limited,
    Opt_Range_Limited_Desc,
    Opt_Range_Full,
    Opt_Range_Full_Desc,

    Opt_Matrix_Auto,
    Opt_Matrix_Auto_Desc,
    Opt_Matrix_601,
    Opt_Matrix_601_Desc,
    Opt_Matrix_709,
    Opt_Matrix_709_Desc,
    Opt_Matrix_2020,
    Opt_Matrix_2020_Desc,

    Opt_Lang_System,
    Opt_Lang_System_Desc,
    Opt_Lang_En,
    Opt_Lang_En_Desc,
    Opt_Lang_Vi,
    Opt_Lang_Vi_Desc,

    Opt_Audio_SystemDefault,
    Opt_Audio_SystemDefault_Desc,
    Opt_Audio_DirectEndpoint_Desc,

    Opt_Mon_Primary,
    Opt_Mon_Primary_Desc,
    Opt_Mon_Secondary,
    Opt_Mon_Secondary_Desc,
    Opt_Mon_Current,
    Opt_Mon_Current_Desc,

    // General page
    General_Language,
    General_Language_System,
    General_Language_En,
    General_Language_Vi,
    General_StartOnBoot,
    General_StartMinimized,
    General_AlwaysOnTop,
    General_StartWithWindows,
    General_MinimizeToTray,
    General_RememberWindowPos,
    General_AllowPublicNetworks,
    Network_PublicWarning,
    Network_OpenNetworkSettings,
    Network_AllowOnThisNetwork,
    Network_PublicSecurityTitle,
    Network_PublicSecurityPrompt,
    Network_PublicUacDenied,
    Network_PublicDisableUacDenied,
    Network_PublicMismatchWarning,
    Network_PublicRulesMissingWarning,
    Network_RepairPublicRules,
    Network_DisablePublicRules,

    // Output page
    Output_Resolution,
    Output_Quality,
    Output_CaptureCanvas,
    Output_AspectMode,
    Output_ScalingQuality,
    Output_PixelPerfect,
    Output_Renderer,
    Output_Profile,
    Output_ColorPreset,
    Output_Brightness,
    Output_Contrast,
    Output_Saturation,
    Output_Hue,
    Output_Sharpness,
    Output_ColorRange,
    Output_ColorMatrix,
    Output_Reset,
    Output_AutoOpenOutputWindow,
    Output_StartFullscreen,
    Output_PreferredMonitor,
    Output_HideCursor,
    Output_RememberOutputPos,

    // Audio page
    Audio_OutputDevice,
    Audio_SystemDefault,
    Audio_Mute,
    Audio_Volume,
    Audio_SyncOffset,
    Audio_TestButton,
    Audio_Diagnostics,
    Audio_SessionName,
    Audio_BufferMs,
    Audio_Underruns,
    Audio_SessionNameLbl,
    Audio_FormatLbl,
    Audio_FormatVal,
    Audio_BufferLbl,
    Audio_UnderrunsLbl,
    Audio_DeviceLbl,
    Audio_PlayTestTone,

    // Privacy & Legal page
    Privacy_Title,
    Privacy_OpenSource,
    Privacy_ThirdParty,
    Privacy_License,
    Privacy_NoTelemetry,
    Privacy_NoDataExternal,
    Privacy_OpenSourceDesc,
    Privacy_ThirdPartyComponents,
    Privacy_ThirdPartyMore,
    Privacy_SeeNotices,

    // Advanced page
    Adv_Title,
    Adv_DebugLog,
    Adv_FlushPipeline,
    Adv_Renderer,
    Adv_Profile,

    // About page
    About_VersionTitle,
    About_Title,
    About_Desc,
    About_Copyright,
    About_Btn_CopyDiag,
    About_Btn_OpenLogs,
    About_Btn_Notices,
    About_Btn_GitHub,
    About_DiagCopied,
    About_OpenSourceSummary,
    About_SpecLead,
    About_SpecUi,
    About_SpecVideo,
    About_SpecPres,
    About_SpecAudio,
    About_SpecCapture,
    About_Footer,

    // First-Run Experience
    FirstRun_Title,
    FirstRun_Desc,
    FirstRun_AirPlay_Title,
    FirstRun_AirPlay_Desc,
    FirstRun_Wired_Title,
    FirstRun_Wired_Desc,
    FirstRun_Btn_Continue,

    // Crash Recovery Banner
    Crash_Banner_Text,
    Crash_Banner_OpenLogs,
    Crash_Banner_Dismiss,

    // Common actions
    Common_Save,
    Common_Reset,
    Common_Cancel,
    Common_Apply,
    Common_On,
    Common_Off,
    Common_Auto,
    Common_Custom,
    Common_Default,
    Common_Test,

    // Dual connection modes
    Nav_Audio,
    Mode_Title,
    Mode_Wireless,
    Mode_Wired,
    Wireless_Description,
    Wireless_StepsTitle,
    Wireless_Step1,
    Wireless_Step2,
    Wireless_Step3,
    Wireless_RestartService,
    Wired_Description,
    Wired_StatusTitle,
    Wired_NoCable,
    Wired_DeviceDetected,
    Wired_DriverMissing,
    Wired_ServiceStopped,
    Wired_VideoBridgeUnavailable,
    Wired_TrustUnknown,
    Wired_UsbInterfaces,
    Wired_AppleRuntime,
    Wired_Trust,
    Wired_Session,
    Wired_Model,
    Wired_IosVersion,
    Wired_Battery,
    Wired_Speed,
    Wired_Unknown,
    Wired_StepsTitle,
    Wired_Step1,
    Wired_Step2,
    Wired_Step3,
    Wired_Step4,
    Wired_Refresh,
    Wired_Start,
    Wired_Troubleshoot,
    Wired_TransportUnavailable,
    Wired_NoWirelessFallback,
    Wired_Cable,
    Wired_DeviceName,
    Wired_RuntimeRunning,
    Wired_RuntimeStopped,
    Wired_RuntimeMissing,
    Wired_Searching,
    Audio_CurrentEndpoint,
    Audio_DeviceUnavailable,
    General_RememberMode,
    General_DefaultMode,
    Adv_OpenLogs,
    Adv_OpenSettingsFile,
    Audio_PlaybackSection,
    Audio_StatusSection,
    Audio_TroubleshootSection,
    Audio_VolumeNote,

    // Wired USB Device Control (CoreDevice HID)
    Wired_DeviceControl,
    Wired_ControlActive,
    Wired_ControlReady,
    Wired_ControlStarting,
    Wired_ControlConnectingRsd,
    Wired_ControlOpeningHid,
    Wired_ControlError,
    Wired_ControlDisabled,
    Wired_ControlConnectedNoVideo,
    Wired_BtnHome,
    Wired_BtnLock,
    Wired_BtnVolDown,
    Wired_BtnVolUp,
    Wired_BtnMute,
    Wired_BtnSiri,
    Wired_DisableControl,
    Wired_EnableControl,
    Wired_ScreenMirroring,
    Wired_WaitingVideoStream,
    Wired_ShortcutsHint,
    Wired_LatencyTelemetry,
    Wired_PreparingUsbNetwork,
    Wired_EnablePersonalHotspot,
    Wired_ReconnectMirroring,
    Video_HevcUnavailable,
    Wired_RoutingFailure,
    Video_DecoderInitFailure,

    _COUNT
};

// Get localized string for the given ID. Returns a static pointer — never null.
// Thread-safe for reads; call SetLang() only from the main thread.
const wchar_t* Get(S id) noexcept;

// Set language. Lang::System resolves via GetUserDefaultUILanguage().
// Call from main thread only. Triggers no UI invalidation — caller must redraw.
void SetLang(Lang lang) noexcept;

// Return currently active language (System already resolved to En or Vi).
Lang CurrentLang() noexcept;

} // namespace duwn::ui::loc
