#include "Loc.h"
#include <array>
#include <cstddef>

namespace duwn::ui::loc {

// ---------------------------------------------------------------------------
// English strings (en-US)
// ---------------------------------------------------------------------------
static constexpr const wchar_t* kEn[static_cast<size_t>(S::_COUNT)] = {
    /* Nav_Mirror                   */ L"Mirror",
    /* Nav_Performance              */ L"Performance",
    /* Nav_Video                    */ L"Video",
    /* Nav_Settings                 */ L"Settings",
    /* Nav_About                    */ L"About",

    /* Settings_General             */ L"General",
    /* Settings_Output              */ L"Output",
    /* Settings_Network             */ L"Network",
    /* Settings_Audio               */ L"Audio",
    /* Settings_Privacy             */ L"Privacy & Legal",
    /* Settings_Advanced            */ L"Advanced",

    /* Header_Subtitle              */ L"IPHONE SCREEN CONNECTION FOR WINDOWS",
    /* Header_AboutTooltip          */ L"About Duwn Mirror",

    /* Status_Idle                  */ L"Idle",
    /* Status_Ready                 */ L"Ready to connect",
    /* Status_Connecting            */ L"Connecting…",
    /* Status_Connected             */ L"Connected",
    /* Status_ConnectedWaitingVideo */ L"Connected, waiting for video…",
    /* Status_Streaming             */ L"Streaming",
    /* Status_Paused                */ L"Paused (Static)",
    /* Status_Reconnecting          */ L"Reconnecting…",
    /* Status_Disconnecting         */ L"Disconnecting…",
    /* Status_Disconnected          */ L"Disconnected",
    /* Status_Error                 */ L"Error",
    /* Status_StartingAirPlay       */ L"Starting AirPlay…",
    /* Status_AirPlayRuntimeError   */ L"AirPlay Runtime Error",
    /* Status_Dot_Streaming         */ L"● Streaming",
    /* Status_Dot_Connected         */ L"● Connected",
    /* Status_Dot_Paused            */ L"● Paused",
    /* Status_Dot_Connecting        */ L"● Connecting",
    /* Status_Dot_Disconnecting     */ L"● Disconnecting",
    /* Status_Dot_Error             */ L"● Error",
    /* Status_Dot_Ready             */ L"● Ready",
    /* Status_Dot_Idle              */ L"● Idle",
    /* Status_PausedStaticScreen    */ L"● PAUSED (STATIC SCREEN)",
    /* Status_AirPlayStreamActive   */ L"● AIRPLAY STREAM ACTIVE",
    /* Status_WaitingAirPlayConn    */ L"Waiting for AirPlay connection",
    /* Status_EngineReadyPorts      */ L"Local RTP/UDP Engine Ready • Port 7000/7100 Listening",

    /* Sidebar_ZeroCopyTitle        */ L"ZERO-COPY PIPELINE",
    /* Sidebar_ZeroCopyDesc         */ L"D3D11 NV12 Hardware Decode\nDXGI Flip-Discard 60 FPS\nDirect IPC Shared Ring",

    /* Mirror_NoStream              */ L"No stream",
    /* Mirror_WaitingAirPlay        */ L"Waiting for AirPlay…",
    /* Mirror_DeviceName            */ L"Device",
    /* Mirror_Resolution            */ L"Resolution",
    /* Mirror_FrameRate             */ L"Frame rate",
    /* Mirror_ConnectedTo           */ L"Connected to",
    /* Mirror_ActiveStream          */ L"ACTIVE AIRPLAY STREAM",
    /* Mirror_StreamStatus          */ L"AIRPLAY STREAM STATUS",
    /* Mirror_RealtimeBroadcast     */ L"REALTIME BROADCAST FEED",
    /* Mirror_ReadyForSender        */ L"READY FOR SENDER CONNECTION",
    /* Mirror_AppleDevice           */ L"Apple Device",
    /* Mirror_NoDeviceConnected     */ L"No Device Connected",
    /* Mirror_HardwareD3D11Note     */ L"Hardware Accelerated (D3D11) • Local RTP/UDP",
    /* Mirror_Metric_Resolution     */ L"RESOLUTION",
    /* Mirror_Metric_FrameRate      */ L"FRAME RATE",
    /* Mirror_Metric_AudioEngine    */ L"AUDIO ENGINE",
    /* Mirror_Metric_SessionUptime  */ L"SESSION UPTIME",
    /* Mirror_Metric_FrameDrops     */ L"FRAME DROPS",
    /* Mirror_Metric_PipelineLag    */ L"PIPELINE LAG",
    /* Mirror_Static                */ L"Static",
    /* Mirror_OutputOpenObsActive   */ L"Dedicated Output Window Open (OBS Active)",
    /* Mirror_OpenOutputForObs      */ L"Open Output Window for OBS Studio",
    /* Mirror_ZeroCopyPresenting    */ L"Zero-copy HWND surface is presenting at 60 FPS with DXGI flip-discard.",
    /* Mirror_CleanHwndDesc         */ L"Creates a clean, borderless HWND for game streaming and window capture.",
    /* Mirror_DirectCaptureActive   */ L"DirectCapture Mode Active",
    /* Mirror_LaunchOutputWindow    */ L"Launch Output Window",
    /* Mirror_ConnectedToDevice     */ L"Connected to: ",
    /* Mirror_WaitingAirPlayHeader  */ L"WAITING FOR AIRPLAY CONNECTION",
    /* Mirror_WaitingAirPlaySub     */ L"Open Control Center on your iPhone or iPad, tap Screen Mirroring, and select \"Duwn Mirror\" to start streaming immediately.",
    /* Mirror_ZeroCopyD3D11         */ L"Zero-Copy D3D11 NV12",
    /* Mirror_WasapiAudioClock      */ L"WASAPI Audio Clock",
    /* Mirror_DxgiFlipDiscard       */ L"DXGI Flip-Discard",
    /* Mirror_Guide_Step1           */ L"1. Open Control Center on your iPhone",
    /* Mirror_Guide_Step2           */ L"2. Tap Screen Mirroring [⧉]",
    /* Mirror_Guide_Step3           */ L"3. Select \"Duwn Mirror\"",
    /* Mirror_EngineNote            */ L"Hardware NV12 • Zero Lock Contention • OBS & TikTok Live Studio Ready",
    /* Mirror_Empty_Wireless_Title  */ L"Wireless AirPlay",
    /* Mirror_Empty_Wireless_Desc   */ L"Open Screen Mirroring on your iPhone or iPad and select Duwn Mirror.",
    /* Mirror_Empty_Wired_NoCable   */ L"Connect your iPhone or iPad with a USB cable.",
    /* Mirror_Empty_Wired_Preparing */ L"Preparing USB connection...",
    /* Mirror_Empty_Wired_Ready     */ L"Ready for wired mirroring.",
    /* Mirror_Waiting_Video         */ L"Waiting for video...",
    /* Mirror_WindowsTitle          */ L"WINDOWS",
    /* Mirror_Btn_ShowPreview       */ L"Show Preview",
    /* Mirror_Btn_HidePreview       */ L"Hide Preview",
    /* Mirror_Btn_ShowOutput        */ L"Show Output",
    /* Mirror_Btn_HideOutput        */ L"Hide Output",
    /* Mirror_Btn_FullscreenPreview */ L"Fullscreen Preview",
    /* Mirror_Toggle_AlwaysOnTop    */ L"Always on Top",

    /* Right_DeviceConnection       */ L"DEVICE CONNECTION",
    /* Right_LocalRtpStream         */ L"Local RTP/UDP Stream",
    /* Right_Btn_Apply              */ L"Apply",
    /* Right_Btn_Eject              */ L"Eject",
    /* Right_Btn_Refresh            */ L"Refresh",
    /* Right_Signal                 */ L"Signal",
    /* Right_RealtimeTelemetry      */ L"REALTIME TELEMETRY",
    /* Right_Tile_Decoder           */ L"Decoder",
    /* Right_Tile_RenderFps         */ L"Render FPS",
    /* Right_Tile_QueuePacing       */ L"Queue Pacing",
    /* Right_Tile_AvLag             */ L"AV Lag",
    /* Right_FramesPlural           */ L"Frames",
    /* Right_FrameSingular          */ L"Frame",
    /* Right_OutputControls         */ L"OUTPUT CONTROLS",
    /* Right_OutputWindowActive     */ L"Hide Output",
    /* Right_ShowOutputWindow       */ L"Show Output",
    /* Right_Btn_Full               */ L"Fullscreen",
    /* Right_Btn_Aspect             */ L"Aspect",
    /* Right_Btn_Pin                */ L"Always on Top",
    /* Right_Btn_Unmute             */ L"Unmute",
    /* Right_Btn_Mute               */ L"Mute",
    /* Right_CreatorTipsHeader      */ L"OBS / TIKTOK LIVE STUDIO CAPTURE",
    /* Right_CreatorTipsDesc        */ L"Add Window Capture in OBS and select \"Duwn Mirror Output\" with Windows Graphics Capture (WGC) for zero-copy 60 FPS streaming.",

    /* Perf_Title                   */ L"Performance",
    /* Perf_SourceFps               */ L"Source FPS",
    /* Perf_DecodedFps              */ L"Decoded FPS",
    /* Perf_PresentedFps            */ L"Presented FPS",
    /* Perf_EncoderFps              */ L"Encoder FPS",
    /* Perf_SourceRes               */ L"Source resolution",
    /* Perf_CaptureCanvas           */ L"Capture canvas",
    /* Perf_PreviewWindow           */ L"Preview window",
    /* Perf_AudioBuffer             */ L"Audio buffer",
    /* Perf_Underruns               */ L"Underruns",
    /* Perf_Uptime                  */ L"Uptime",
    /* Perf_DiagnosticsTitle        */ L"Pipeline Performance & Diagnostics",
    /* Perf_DiagnosticsSub          */ L"Direct hardware clock, jitter buffer, and DXGI presentation telemetry",
    /* Perf_FlushPipeline           */ L"Flush Pipeline",
    /* Perf_VideoDecodeRender       */ L"VIDEO DECODE & RENDER",
    /* Perf_Lbl_RequestedInput      */ L"Encoder Requested Input",
    /* Perf_Lbl_ActualSource        */ L"Actual Visible Source",
    /* Perf_Lbl_SourceFps           */ L"Source Delivery FPS",
    /* Perf_Lbl_DecodedPresented    */ L"Decoded / Presented",
    /* Perf_Lbl_Decoder             */ L"Decoder",
    /* Perf_Lbl_QueueDrops          */ L"Queue / Drops",
    /* Perf_PresDxgiClock           */ L"PRESENTATION & DXGI CLOCK",
    /* Perf_Lbl_Source              */ L"Source",
    /* Perf_Lbl_CaptureCanvas       */ L"Capture Canvas",
    /* Perf_Lbl_PreviewWindow       */ L"Preview Window",
    /* Perf_Lbl_RendererSurface     */ L"Renderer",
    /* Perf_Lbl_ScalerLatency       */ L"Scaler / Latency",
    /* Perf_AudioWasapiClock        */ L"AUDIO & WASAPI CLOCK",
    /* Perf_Lbl_AudioStatus         */ L"Audio Status",
    /* Perf_Lbl_EngineFormat        */ L"Engine Format: WASAPI 48000 Hz Stereo (Float32)",
    /* Perf_Lbl_AudioClock          */ L"Audio Clock: Continuous Resampler Clock",
    /* Perf_Lbl_AudioMuteState      */ L"Mute State",
    /* Perf_Lbl_RealUnderruns       */ L"Real Underruns",
    /* Perf_Active                  */ L"Active",
    /* Perf_MutedSilentBuffer       */ L"Muted (Silent Buffer)",
    /* Perf_UnmutedPlaying          */ L"Unmuted (Playing)",
    /* Perf_TransportIpc            */ L"AIRPLAY TRANSPORT & IPC",
    /* Perf_Lbl_Protocol            */ L"AirPlay Protocol: RTSP / RTP (Ports 7000, 7001, 7100)\n",
    /* Perf_Lbl_TransportMode       */ L"Transport Mode",
    /* Perf_Lbl_SidecarStatus       */ L"Sidecar Status",
    /* Perf_Lbl_VideoRtpPackets     */ L"Video RTP Packets",
    /* Perf_Lbl_AudioRtpPackets     */ L"Audio RTP Packets",
    /* Perf_MissingError            */ L"Missing / Error",
    /* Perf_ResolutionWarning       */ L"Output resolution is lower than the AirPlay source. Choose Match Source or higher output quality.",

    /* Video_Title                  */ L"Video",
    /* Video_Subtitle               */ L"Configure AirPlay receiver quality, canvas presentation, GPU rendering, and real-time color grading",
    /* Video_QuickSetup             */ L"QUICK SETUP",
    /* Video_AirPlayInput           */ L"AIRPLAY INPUT",
    /* Video_ReceiverQuality        */ L"Receiver Quality",
    /* Video_Requested              */ L"Requested",
    /* Video_ActualSource           */ L"Actual Source",
    /* Video_Quality_DeliveredAsRequested */ L"Delivered as requested",
    /* Video_Quality_SourceLimited        */ L"Source limited by device",
    /* Video_Quality_PartiallyDelivered   */ L"Partially delivered",
    /* Video_PendingReconnect       */ L"Pending reconnect to apply new preset",
    /* Video_SidecarActive          */ L"Receiver Active",
    /* Video_Delivery                */ L"DISPLAY LATENCY",
    /* Video_DeliveryMode            */ L"Delivery mode",
    /* Video_Freshness               */ L"Catch up after",
    /* Video_QueueFrames             */ L"Pending frames",
    /* Video_DeliveryHint            */ L"Applies now • Keeps selected resolution/FPS",
    /* Opt_Delivery_Balanced         */ L"Balanced",
    /* Opt_Delivery_Balanced_Desc    */ L"Preserve fresh frames; catch up when the queue falls behind",
    /* Opt_Delivery_Fastest          */ L"Fastest",
    /* Opt_Delivery_Fastest_Desc     */ L"Keep the newest decoded image; may skip frames during bursts",
    /* Opt_Delivery_Smooth           */ L"Prefer smoothness",
    /* Opt_Delivery_Smooth_Desc      */ L"Retain up to three frames with a larger catch-up threshold",
    /* Opt_Delivery_Custom           */ L"Custom",
    /* Opt_Delivery_Custom_Desc      */ L"Set pending frames and catch-up threshold independently of quality",
    /* Video_Output                 */ L"OUTPUT",
    /* Video_AutoMatchSource        */ L"Auto (Match Source)",
    /* Video_AspectFitBars          */ L"Fit (Bars)",
    /* Video_AspectFillCrop         */ L"Fill (Crop)",
    /* Video_AspectStretch          */ L"Stretch",
    /* Video_AspectAuto             */ L"Auto",
    /* Video_CanvasMatchDesc        */ L"Ready — Output canvas will dynamically follow incoming source without black bars.",
    /* Video_Rendering              */ L"RENDERING",
    /* Video_RendererMode           */ L"Renderer Mode",
    /* Video_Resolved               */ L"Resolved Output",
    /* Video_ZeroCopyActive         */ L"Active (NV12)",
    /* Video_ZeroCopyDisabled       */ L"Disabled",
    /* Video_Color                  */ L"COLOR",
    /* Video_Live                   */ L"LIVE",
    /* Video_ResetToZeroTooltip     */ L"Double-click to reset to 0",
    /* Video_ResetTooltip           */ L"Reset to 0",
    /* Video_FilterNotSupported     */ L"Filter not supported by active renderer",
    /* Video_AdvColorOverview       */ L"ADVANCED COLOR & PIPELINE OVERVIEW",
    /* Video_Collapse               */ L"Collapse",
    /* Video_Expand                 */ L"Expand",
    /* Video_ActiveCanvas           */ L"Active Canvas: {}×{} ({})\n",
    /* Video_AspectBehavior         */ L"Aspect Behavior: {}\n",
    /* Video_ColorPipeline          */ L"Color Pipeline: {}, {}",
    /* Video_Fixed                  */ L"Fixed",
    /* Video_AutoFollowsStream      */ L"Auto (Follows Stream)",
    /* Video_AutoRange              */ L"Auto Range",
    /* Video_AutoMatrix             */ L"Auto Matrix",

    /* Opt_Profile_Auto             */ L"Auto",
    /* Opt_Profile_Auto_Desc        */ L"Balanced latency and visual fidelity",
    /* Opt_Profile_HighQuality      */ L"High Quality",
    /* Opt_Profile_HighQuality_Desc */ L"Best fidelity, bicubic scaling, NV12 zero-copy",
    /* Opt_Profile_Balanced         */ L"Balanced",
    /* Opt_Profile_Balanced_Desc    */ L"Low latency, adaptive hardware blit",
    /* Opt_Profile_LowSpec          */ L"Low Spec",
    /* Opt_Profile_LowSpec_Desc     */ L"Prioritizes responsiveness on low-end hardware",
    /* Opt_Profile_Custom           */ L"Custom",
    /* Opt_Profile_Custom_Desc      */ L"Manual overrides active",

    /* Opt_Rec_Auto                 */ L"Auto",
    /* Opt_Rec_Auto_Desc            */ L"Automatically selects best stable quality",
    /* Opt_Rec_720p30               */ L"HD · 30 FPS",
    /* Opt_Rec_720p30_Desc          */ L"Resource saver",
    /* Opt_Rec_720p60               */ L"HD · 60 FPS",
    /* Opt_Rec_720p60_Desc          */ L"Smoother for motion",
    /* Opt_Rec_1080p30              */ L"Full HD · 30 FPS",
    /* Opt_Rec_1080p30_Desc         */ L"High quality",
    /* Opt_Rec_1080p60              */ L"Full HD · 60 FPS",
    /* Opt_Rec_1080p60_Desc         */ L"High quality, smoother",
    /* Opt_Rec_1440p60              */ L"2K · 60 FPS",
    /* Opt_Rec_1440p60_Desc         */ L"Very high quality · Experimental",
    /* Opt_Rec_Original60           */ L"Original · 60 FPS",
    /* Opt_Rec_Original60_Desc      */ L"1:1 source passthrough at 60 FPS (no downscaling)",

    /* Opt_Out_Auto                 */ L"Auto",
    /* Opt_Out_Auto_Desc            */ L"Matches actual visible source dimensions",
    /* Opt_Out_HD                   */ L"HD",
    /* Opt_Out_HD_Desc              */ L"Long edge ~1280 (preserves source aspect ratio)",
    /* Opt_Out_FullHD               */ L"Full HD",
    /* Opt_Out_FullHD_Desc          */ L"Long edge ~1920 (preserves source aspect ratio)",
    /* Opt_Out_2K                   */ L"2K",
    /* Opt_Out_2K_Desc              */ L"Long edge ~2560 (preserves source aspect ratio)",
    /* Opt_Out_4K                   */ L"4K",
    /* Opt_Out_4K_Desc              */ L"Long edge ~3840 (preserves source aspect ratio)",
    /* Opt_Out_Original             */ L"Original",
    /* Opt_Out_Original_Desc        */ L"1:1 source passthrough (no downscaling)",
    /* Opt_Out_Custom               */ L"Custom…",
    /* Opt_Out_Custom_Desc          */ L"Specify custom dimensions",

    /* Opt_Canvas_FollowSource      */ L"Follow Source",
    /* Opt_Canvas_FollowSource_Desc */ L"Aspect-aware output derived from source (no letterbox)",
    /* Opt_Canvas_16_9_HD           */ L"16:9 HD",
    /* Opt_Canvas_16_9_HD_Desc      */ L"1280×720 broadcast canvas",
    /* Opt_Canvas_16_9_FullHD       */ L"16:9 Full HD",
    /* Opt_Canvas_16_9_FullHD_Desc  */ L"1920×1080 broadcast canvas",
    /* Opt_Canvas_16_9_2K           */ L"16:9 2K",
    /* Opt_Canvas_16_9_2K_Desc      */ L"2560×1440 broadcast canvas",
    /* Opt_Canvas_Custom            */ L"Custom…",
    /* Opt_Canvas_Custom_Desc       */ L"Custom broadcast canvas",

    /* Opt_Aspect_Preserve          */ L"Preserve Source Ratio",
    /* Opt_Aspect_Preserve_Desc     */ L"Maintains source aspect ratio without bars or cropping",
    /* Opt_Aspect_Auto              */ L"Auto",
    /* Opt_Aspect_Auto_Desc         */ L"Matches source in Match Source; Fit on fixed canvas",
    /* Opt_Aspect_Fit               */ L"Fit",
    /* Opt_Aspect_Fit_Desc          */ L"Letterbox / pillarbox bars; preserves aspect ratio",
    /* Opt_Aspect_Fill              */ L"Fill",
    /* Opt_Aspect_Fill_Desc         */ L"Center-crop; fills entire canvas with no bars",
    /* Opt_Aspect_Stretch           */ L"Stretch",
    /* Opt_Aspect_Stretch_Desc      */ L"Distorts to fill canvas with no bars",

    /* Opt_Scale_Auto               */ L"Auto (Recommended)",
    /* Opt_Scale_Auto_Desc          */ L"Adaptive hardware scaling",
    /* Opt_Scale_Fast               */ L"Fast",
    /* Opt_Scale_Fast_Desc          */ L"Linear / hardware nearest",
    /* Opt_Scale_Sharp              */ L"Sharp",
    /* Opt_Scale_Sharp_Desc         */ L"Bilinear with adaptive edge enhancement",
    /* Opt_Scale_HighQuality        */ L"High Quality",
    /* Opt_Scale_HighQuality_Desc   */ L"Bicubic / multi-tap filtering",

    /* Opt_Pixel_Auto               */ L"Auto",
    /* Opt_Pixel_Auto_Desc          */ L"1:1 pixel mapping when sizes match, single scale otherwise",
    /* Opt_Pixel_On                 */ L"On",
    /* Opt_Pixel_On_Desc            */ L"Strict integer 1:1 pixel mapping, centered",
    /* Opt_Pixel_Off                */ L"Off",
    /* Opt_Pixel_Off_Desc           */ L"Always scale to fit destination canvas",

    /* Opt_Rnd_Auto                 */ L"Auto (Recommended)",
    /* Opt_Rnd_Auto_Desc            */ L"Selects fastest zero-copy hardware pipeline",
    /* Opt_Rnd_D3D11                */ L"Hardware D3D11",
    /* Opt_Rnd_D3D11_Desc           */ L"Direct Video Processor Zero-Copy (Fastest)",
    /* Opt_Rnd_Compat               */ L"Compatibility",
    /* Opt_Rnd_Compat_Desc          */ L"Direct3D 11 Blit Fallback",
    /* Opt_Rnd_Warp                 */ L"Software / CPU",
    /* Opt_Rnd_Warp_Desc            */ L"WARP Software Emulation (High CPU)",

    /* Opt_Color_Neutral            */ L"Neutral",
    /* Opt_Color_Neutral_Desc       */ L"Standard uncalibrated stream colors (all 0)",
    /* Opt_Color_Vivid              */ L"Vivid",
    /* Opt_Color_Vivid_Desc         */ L"Enhanced punch, contrast and saturation for games",
    /* Opt_Color_Soft               */ L"Soft",
    /* Opt_Color_Soft_Desc          */ L"Muted contrast and saturation for reading / UI",
    /* Opt_Color_Custom             */ L"Custom",
    /* Opt_Color_Custom_Desc        */ L"Custom user slider adjustments",

    /* Opt_Range_Auto               */ L"Auto",
    /* Opt_Range_Auto_Desc          */ L"Follow stream metadata",
    /* Opt_Range_Limited            */ L"Limited (16-235)",
    /* Opt_Range_Limited_Desc       */ L"16-235 TV standard",
    /* Opt_Range_Full               */ L"Full (0-255)",
    /* Opt_Range_Full_Desc          */ L"0-255 PC standard",

    /* Opt_Matrix_Auto              */ L"Auto",
    /* Opt_Matrix_Auto_Desc         */ L"BT.709 for HD, BT.601 for SD",
    /* Opt_Matrix_601               */ L"BT.601",
    /* Opt_Matrix_601_Desc          */ L"SD / Legacy color standard",
    /* Opt_Matrix_709               */ L"BT.709",
    /* Opt_Matrix_709_Desc          */ L"HD / Modern standard",
    /* Opt_Matrix_2020              */ L"BT.2020",
    /* Opt_Matrix_2020_Desc         */ L"UHD / Wide Gamut standard",

    /* Opt_Lang_System              */ L"System Default",
    /* Opt_Lang_System_Desc         */ L"Auto-detect English / Tiếng Việt",
    /* Opt_Lang_En                  */ L"English",
    /* Opt_Lang_En_Desc             */ L"English (United States)",
    /* Opt_Lang_Vi                  */ L"Tiếng Việt",
    /* Opt_Lang_Vi_Desc             */ L"Tiếng Việt (Việt Nam)",

    /* Opt_Audio_SystemDefault      */ L"System Default",
    /* Opt_Audio_SystemDefault_Desc */ L"Windows default multimedia render endpoint",
    /* Opt_Audio_DirectEndpoint_Desc*/ L"Direct render endpoint",

    /* Opt_Mon_Primary              */ L"Primary Monitor",
    /* Opt_Mon_Primary_Desc         */ L"Default Windows primary display",
    /* Opt_Mon_Secondary            */ L"Secondary Monitor",
    /* Opt_Mon_Secondary_Desc       */ L"Display index 1",
    /* Opt_Mon_Current              */ L"Current Monitor",
    /* Opt_Mon_Current_Desc         */ L"Display where main window resides",

    /* General_Language             */ L"Language",
    /* General_Language_System      */ L"System Default",
    /* General_Language_En          */ L"English",
    /* General_Language_Vi          */ L"Tiếng Việt",
    /* General_StartOnBoot          */ L"Start on boot",
    /* General_StartMinimized       */ L"Start minimized",
    /* General_AlwaysOnTop          */ L"Always on top",
    /* General_StartWithWindows     */ L"Start with Windows",
    /* General_MinimizeToTray       */ L"Minimize to system tray",
    /* General_RememberWindowPos    */ L"Remember window position",
    /* General_AllowPublicNetworks  */ L"Allow AirPlay on public networks",
    /* Network_PublicWarning        */ L"Current network is Public. Windows Firewall may block AirPlay connections.",
    /* Network_OpenNetworkSettings  */ L"Open Network Settings",
    /* Network_AllowOnThisNetwork   */ L"Allow on this network",
    /* Network_PublicSecurityTitle  */ L"Public Network AirPlay — Security Warning",
    /* Network_PublicSecurityPrompt */ L"Enabling AirPlay on public networks allows incoming connections from any device on this untrusted network (e.g. coffee shop, hotel, airport Wi-Fi).\n\nThis requires administrator approval (UAC) to configure Windows Defender Firewall for duwn-mirror.exe and uxplay.exe.\n\nDo you want to proceed?",
    /* Network_PublicUacDenied          */ L"Administrator permission was denied or firewall rules could not be created. AirPlay remains disabled on public networks.",
    /* Network_PublicDisableUacDenied   */ L"Administrator permission is required to remove the Public network firewall rules.",
    /* Network_PublicMismatchWarning    */ L"Public network firewall rules are currently active in Windows Defender Firewall.",
    /* Network_PublicRulesMissingWarning*/ L"Settings had public networks enabled, but Windows Firewall rules are missing. AirPlay on public networks has been disabled for safety.",
    /* Network_RepairPublicRules        */ L"Repair Firewall Rules",
    /* Network_DisablePublicRules       */ L"Disable Public Rules",

    /* Output_Resolution            */ L"Resolution",
    /* Output_Quality               */ L"Output Quality",
    /* Output_CaptureCanvas         */ L"Capture Canvas",
    /* Output_AspectMode            */ L"Aspect mode",
    /* Output_ScalingQuality        */ L"Scaling quality",
    /* Output_PixelPerfect          */ L"Pixel perfect",
    /* Output_Renderer              */ L"Renderer",
    /* Output_Profile               */ L"Profile",
    /* Output_ColorPreset           */ L"Color preset",
    /* Output_Brightness            */ L"Brightness",
    /* Output_Contrast              */ L"Contrast",
    /* Output_Saturation            */ L"Saturation",
    /* Output_Hue                   */ L"Hue",
    /* Output_Sharpness             */ L"Sharpness",
    /* Output_ColorRange            */ L"Color range",
    /* Output_ColorMatrix           */ L"Color matrix",
    /* Output_Reset                 */ L"Reset to defaults",
    /* Output_AutoOpenOutputWindow  */ L"Automatically open Output Window",
    /* Output_StartFullscreen       */ L"Start fullscreen",
    /* Output_PreferredMonitor      */ L"Preferred monitor",
    /* Output_HideCursor            */ L"Hide cursor over video",
    /* Output_RememberOutputPos     */ L"Remember Output Window position",

    /* Audio_OutputDevice           */ L"Output device",
    /* Audio_SystemDefault          */ L"System Default",
    /* Audio_Mute                   */ L"Mute audio",
    /* Audio_Volume                 */ L"Volume",
    /* Audio_SyncOffset             */ L"Sync offset (ms)",
    /* Audio_TestButton             */ L"Test audio",
    /* Audio_Diagnostics            */ L"Diagnostics",
    /* Audio_SessionName            */ L"Session name",
    /* Audio_BufferMs               */ L"Buffer",
    /* Audio_Underruns              */ L"Underruns",
    /* Audio_SessionNameLbl         */ L"Session name:",
    /* Audio_FormatLbl              */ L"Format:",
    /* Audio_FormatVal              */ L"48 kHz Stereo Float32 (WASAPI Shared)",
    /* Audio_BufferLbl              */ L"Buffer:",
    /* Audio_UnderrunsLbl           */ L"Underruns:",
    /* Audio_DeviceLbl              */ L"Device:",
    /* Audio_PlayTestTone           */ L"Play test tone",

    /* Privacy_Title                */ L"Privacy & Legal",
    /* Privacy_OpenSource           */ L"Open source software",
    /* Privacy_ThirdParty           */ L"Third-party notices",
    /* Privacy_License              */ L"License",
    /* Privacy_NoTelemetry          */ L"No telemetry or analytics data is collected.",
    /* Privacy_NoDataExternal       */ L"No data is transmitted to external servers.",
    /* Privacy_OpenSourceDesc       */ L"Duwn Mirror is open-source software. Source code is available at:",
    /* Privacy_ThirdPartyComponents */ L"Third-party components: GStreamer (LGPL 2.1+), UxPlay (GPL 3.0),",
    /* Privacy_ThirdPartyMore       */ L"libplist (LGPL 2.1), OpenSSL (Apache 2.0), and others.",
    /* Privacy_SeeNotices           */ L"See THIRD_PARTY_NOTICES.txt in the installation folder.",

    /* Adv_Title                    */ L"Advanced",
    /* Adv_DebugLog                 */ L"Debug logging",
    /* Adv_FlushPipeline            */ L"Flush pipeline",
    /* Adv_Renderer                 */ L"Renderer",
    /* Adv_Profile                  */ L"Performance profile",

    /* About_VersionTitle           */ L"Duwn Mirror",
    /* About_Title                  */ L"About Duwn Mirror",
    /* About_Desc                   */ L"Wireless AirPlay & Wired USB Screen Mirroring for Windows",
    /* About_Copyright              */ L"Copyright © 2026 Duwn Mirror Contributors",
    /* About_Btn_CopyDiag           */ L"Copy Diagnostics",
    /* About_Btn_OpenLogs           */ L"Open Logs Folder",
    /* About_Btn_Notices            */ L"Third-Party Notices",
    /* About_Btn_GitHub             */ L"GitHub",
    /* About_DiagCopied             */ L"Copied to clipboard!",
    /* About_OpenSourceSummary      */ L"Duwn Mirror is built with open source software including UxPlay (GPLv3), GStreamer (LGPL), libplist, OpenSSL, and nlohmann/json.",
    /* About_SpecLead               */ L"Duwn Mirror supports wireless AirPlay mirroring and USB device detection on Windows.\n\n",
    /* About_SpecUi                 */ L"• User Interface: Direct2D & DirectWrite hardware-accelerated control surface (decoupled).\n",
    /* About_SpecVideo              */ L"• Video Pipeline: Microsoft Media Foundation D3D11 NV12 hardware decode.\n",
    /* About_SpecPres               */ L"• Presentation: DXGI Flip-Discard swapchain with Present0 low-latency display pacing.\n",
    /* About_SpecAudio              */ L"• Audio Engine: Windows Audio Session API (WASAPI) with continuous presentation clock.\n",
    /* About_SpecCapture            */ L"• Broadcast Capture: Dedicated clean OutputWindow optimized for OBS Studio and TikTok Live Studio.",
    /* About_Footer                 */ L"Duwn Mirror • Wireless AirPlay & Wired USB Screen Mirroring",

    /* FirstRun_Title               */ L"Welcome to Duwn Mirror",
    /* FirstRun_Desc                */ L"Ultra-fast screen mirroring for iPhone and iPad on Windows.",
    /* FirstRun_AirPlay_Title       */ L"Wireless AirPlay",
    /* FirstRun_AirPlay_Desc        */ L"Mirror instantly over Wi-Fi without cables. Perfect for presentations and casual viewing.",
    /* FirstRun_Wired_Title         */ L"Wired USB",
    /* FirstRun_Wired_Desc          */ L"Ultra-low latency connection over Apple USB cable. Ideal for livestreaming and gaming.",
    /* FirstRun_Btn_Continue        */ L"Get Started",

    /* Crash_Banner_Text            */ L"Duwn Mirror closed unexpectedly during the previous run.",
    /* Crash_Banner_OpenLogs        */ L"Open Logs",
    /* Crash_Banner_Dismiss         */ L"Dismiss",

    /* Common_Save                  */ L"Save",
    /* Common_Reset                 */ L"Reset",
    /* Common_Cancel                */ L"Cancel",
    /* Common_Apply                 */ L"Apply",
    /* Common_On                    */ L"On",
    /* Common_Off                   */ L"Off",
    /* Common_Auto                  */ L"Auto",
    /* Common_Custom                */ L"Custom",
    /* Common_Default               */ L"Default",
    /* Common_Test                  */ L"Test",
    L"Audio", L"CONNECTION MODE", L"Wireless AirPlay", L"Wired USB",
    L"Connect using iPhone Screen Mirroring over Wi-Fi",
    L"CONNECT IN THREE STEPS",
    L"1. Connect iPhone and PC to the same network",
    L"2. Open Screen Mirroring on iPhone",
    L"3. Select Duwn Mirror",
    L"Restart AirPlay Service",
    L"Mirror over the Apple USB connection",
    L"WIRED CONNECTION", L"No USB device connected", L"Apple device detected",
    L"Apple Mobile Device support is missing. Install Apple Devices for Windows.",
    L"Apple Mobile Device Service is stopped. Start the service and reconnect.",
    L"Turn on Personal Hotspot on your iPhone to enable USB networking.",
    L"Cannot verify trust without an Apple device bridge",
    L"USB interfaces", L"Apple runtime", L"Trust", L"Session", L"Model", L"iOS version",
    L"Battery", L"USB speed", L"Unavailable",
    L"TO CONNECT BY CABLE", L"1. Connect iPhone or iPad by USB cable",
    L"2. Unlock the device", L"3. Tap Trust This Computer if prompted",
    L"4. Choose Duwn Mirror in Screen Mirroring",
    L"Refresh USB Devices", L"Check USB Connection", L"Open Device Manager",
    L"Preparing USB connection...", L"Wired uses only Apple USB Ethernet",
    L"Cable", L"Device", L"Service running", L"Service stopped", L"Not installed", L"Scanning USB devices…",
    L"Playing through", L"Selected audio device is unavailable; previous device remains active.",
    L"Remember selected connection mode", L"Default connection mode", L"Open logs folder", L"Open settings file",
    L"PLAYBACK DEVICE", L"AUDIO STATUS", L"TROUBLESHOOTING",
    L"Playback volume follows the selected Windows output device. Mute here affects Duwn Mirror only.",

    /* Wired_DeviceControl           */ L"Device Control",
    /* Wired_ControlActive          */ L"Control active",
    /* Wired_ControlReady           */ L"Control ready",
    /* Wired_ControlStarting        */ L"Starting control bridge…",
    /* Wired_ControlConnectingRsd   */ L"Connecting RSD tunnel…",
    /* Wired_ControlOpeningHid      */ L"Opening HID service…",
    /* Wired_ControlError           */ L"Control error",
    /* Wired_ControlDisabled        */ L"Control off",
    /* Wired_ControlConnectedNoVideo*/ L"Control connected — video unavailable",
    /* Wired_BtnHome                */ L"Home",
    /* Wired_BtnLock                */ L"Power",
    /* Wired_BtnVolDown             */ L"Vol -",
    /* Wired_BtnVolUp               */ L"Vol +",
    /* Wired_BtnMute                */ L"Mute",
    /* Wired_BtnSiri                */ L"Siri",
    /* Wired_DisableControl         */ L"Disable Control",
    /* Wired_EnableControl          */ L"Enable Control",
    /* Wired_ScreenMirroring        */ L"Screen Mirroring",
    /* Wired_WaitingVideoStream     */ L"Waiting for video stream…",
    /* Wired_ShortcutsHint          */ L"Shortcuts: Ctrl+H Home • Ctrl+L Lock • Ctrl+[ Vol- • Ctrl+] Vol+ • Ctrl+S Siri",
    /* Wired_LatencyTelemetry       */ L"Events: {} | Latency P50: {:.1f}ms | P95: {:.1f}ms | Avg: {:.1f}ms",
    /* Wired_PreparingUsbNetwork    */ L"Preparing USB connection...",
    /* Wired_EnablePersonalHotspot  */ L"Turn on Personal Hotspot on your iPhone to enable USB networking.",
    /* Wired_ReconnectMirroring     */ L"If the preview stays black, stop and reconnect Screen Mirroring on your iPhone.",
    /* Video_HevcUnavailable        */ L"Windows HEVC Video Extension is not installed. Install HEVC Video Extensions from Microsoft Store for H.265 support.",
    /* Wired_RoutingFailure         */ L"Wired connection lost or USB tethering disconnected. Check USB cable and Personal Hotspot.",
    /* Video_DecoderInitFailure     */ L"Hardware video decoder failed to initialize for stream format.",
    /* Nav_Color                    */ L"Color",
    /* Nav_Diagnostics              */ L"Diagnostics",
    /* Common_ScreenOnly            */ L"Screen Only",
    /* Common_BackToWorkspace       */ L"Back to Workspace",
    /* Common_QuickVolume           */ L"Quick Volume",
    /* Mirror_Toggle_OutputToolbar  */ L"Show toolbar on output window",
    /* Mirror_Btn_DisconnectSession */ L"Disconnect",
    /* Mirror_Btn_DisconnectDisabledTooltip */ L"No active device connected",
    /* Output_WaitingForFrame       */ L"Waiting for video…",
    /* Output_Fit                   */ L"Fit",
    /* Output_AlwaysOnTop           */ L"Pin",
    /* Output_Fullscreen           */ L"Full",
    /* Output_Mute                  */ L"Mute",
    /* Output_Unmute                */ L"Unmute",
};

// ---------------------------------------------------------------------------
// Vietnamese strings (vi-VN)
// ---------------------------------------------------------------------------
static constexpr const wchar_t* kVi[static_cast<size_t>(S::_COUNT)] = {
    /* Nav_Mirror                   */ L"Màn hình",
    /* Nav_Performance              */ L"Hiệu suất",
    /* Nav_Video                    */ L"Video",
    /* Nav_Settings                 */ L"Cài đặt",
    /* Nav_About                    */ L"Giới thiệu",

    /* Settings_General             */ L"Chung",
    /* Settings_Output              */ L"Đầu ra",
    /* Settings_Network             */ L"Mạng",
    /* Settings_Audio               */ L"Âm thanh",
    /* Settings_Privacy             */ L"Riêng tư & Pháp lý",
    /* Settings_Advanced            */ L"Nâng cao",

    /* Header_Subtitle              */ L"KẾT NỐI MÀN HÌNH IPHONE TRÊN WINDOWS",
    /* Header_AboutTooltip          */ L"Giới thiệu Duwn Mirror",

    /* Status_Idle                  */ L"Chờ",
    /* Status_Ready                 */ L"Sẵn sàng kết nối",
    /* Status_Connecting            */ L"Đang kết nối…",
    /* Status_Connected             */ L"Đã kết nối",
    /* Status_ConnectedWaitingVideo */ L"Đã kết nối, đang chờ hình ảnh",
    /* Status_Streaming             */ L"Đang phát luồng",
    /* Status_Paused                */ L"Tạm dừng (Hình tĩnh)",
    /* Status_Reconnecting          */ L"Đang kết nối lại…",
    /* Status_Disconnecting         */ L"Đang ngắt kết nối…",
    /* Status_Disconnected          */ L"Đã ngắt kết nối",
    /* Status_Error                 */ L"Lỗi",
    /* Status_StartingAirPlay       */ L"Đang khởi động AirPlay…",
    /* Status_AirPlayRuntimeError   */ L"Lỗi thực thi AirPlay",
    /* Status_Dot_Streaming         */ L"● Đang phát",
    /* Status_Dot_Connected         */ L"● Đã kết nối",
    /* Status_Dot_Paused            */ L"● Tạm dừng",
    /* Status_Dot_Connecting        */ L"● Đang kết nối",
    /* Status_Dot_Disconnecting     */ L"● Đang ngắt kết nối",
    /* Status_Dot_Error             */ L"● Lỗi",
    /* Status_Dot_Ready             */ L"● Sẵn sàng",
    /* Status_Dot_Idle              */ L"● Chờ",
    /* Status_PausedStaticScreen    */ L"● TẠM DỪNG (HÌNH TĨNH)",
    /* Status_AirPlayStreamActive   */ L"● LUỒNG AIRPLAY HOẠT ĐỘNG",
    /* Status_WaitingAirPlayConn    */ L"Đang chờ kết nối AirPlay",
    /* Status_EngineReadyPorts      */ L"Bộ xử lý RTP/UDP nội bộ sẵn sàng • Cổng 7000/7100 đang lắng nghe",

    /* Sidebar_ZeroCopyTitle        */ L"LUỒNG XỬ LÝ ZERO-COPY",
    /* Sidebar_ZeroCopyDesc         */ L"Giải mã phần cứng D3D11 NV12\nDXGI Flip-Discard 60 FPS\nBộ đệm chia sẻ IPC trực tiếp",

    /* Mirror_NoStream              */ L"Không có luồng",
    /* Mirror_WaitingAirPlay        */ L"Đang chờ AirPlay…",
    /* Mirror_DeviceName            */ L"Thiết bị",
    /* Mirror_Resolution            */ L"Độ phân giải",
    /* Mirror_FrameRate             */ L"Tốc độ khung hình",
    /* Mirror_ConnectedTo           */ L"Đã kết nối với",
    /* Mirror_ActiveStream          */ L"LUỒNG AIRPLAY HOẠT ĐỘNG",
    /* Mirror_StreamStatus          */ L"TRẠNG THÁI LUỒNG AIRPLAY",
    /* Mirror_RealtimeBroadcast     */ L"NGUỒN PHÁT TRỰC TIẾP",
    /* Mirror_ReadyForSender        */ L"SẴN SÀNG KẾT NỐI TỪ THIẾT BỊ",
    /* Mirror_AppleDevice           */ L"Thiết bị Apple",
    /* Mirror_NoDeviceConnected     */ L"Chưa kết nối thiết bị",
    /* Mirror_HardwareD3D11Note     */ L"Tăng tốc phần cứng (D3D11) • RTP/UDP nội bộ",
    /* Mirror_Metric_Resolution     */ L"ĐỘ PHÂN GIẢI",
    /* Mirror_Metric_FrameRate      */ L"TỐC ĐỘ KHUNG HÌNH",
    /* Mirror_Metric_AudioEngine    */ L"BỘ XỬ LÝ ÂM THANH",
    /* Mirror_Metric_SessionUptime  */ L"THỜI GIAN HOẠT ĐỘNG",
    /* Mirror_Metric_FrameDrops     */ L"KHUNG HÌNH RƠI",
    /* Mirror_Metric_PipelineLag    */ L"ĐỘ TRỄ LUỒNG",
    /* Mirror_Static                */ L"Hình tĩnh",
    /* Mirror_OutputOpenObsActive   */ L"Cửa sổ đầu ra riêng đang mở (OBS Hoạt động)",
    /* Mirror_OpenOutputForObs      */ L"Mở Cửa sổ đầu ra cho OBS Studio",
    /* Mirror_ZeroCopyPresenting    */ L"Bề mặt HWND zero-copy đang hiển thị 60 FPS với DXGI flip-discard.",
    /* Mirror_CleanHwndDesc         */ L"Tạo HWND không viền sạch sẽ phục vụ phát trực tiếp và quay cửa sổ.",
    /* Mirror_DirectCaptureActive   */ L"Chế độ DirectCapture đang hoạt động",
    /* Mirror_LaunchOutputWindow    */ L"Khởi chạy Cửa sổ đầu ra",
    /* Mirror_ConnectedToDevice     */ L"Đã kết nối với: ",
    /* Mirror_WaitingAirPlayHeader  */ L"ĐANG CHỜ KẾT NỐI AIRPLAY",
    /* Mirror_WaitingAirPlaySub     */ L"Mở Trung tâm điều khiển trên iPhone hoặc iPad, chạm vào Phản chiếu màn hình và chọn \"Duwn Mirror\" để bắt đầu truyền ngay lập tức.",
    /* Mirror_ZeroCopyD3D11         */ L"Zero-Copy D3D11 NV12",
    /* Mirror_WasapiAudioClock      */ L"Đồng hồ âm thanh WASAPI",
    /* Mirror_DxgiFlipDiscard       */ L"DXGI Flip-Discard",
    /* Mirror_Guide_Step1           */ L"1. Mở Trung tâm điều khiển trên iPhone",
    /* Mirror_Guide_Step2           */ L"2. Chạm vào Phản chiếu màn hình [⧉]",
    /* Mirror_Guide_Step3           */ L"3. Chọn \"Duwn Mirror\"",
    /* Mirror_EngineNote            */ L"Phần cứng NV12 • Không tắc nghẽn khóa • Sẵn sàng cho OBS & TikTok Live Studio",
    /* Mirror_Empty_Wireless_Title  */ L"Phản chiếu không dây AirPlay",
    /* Mirror_Empty_Wireless_Desc   */ L"Mở Phản chiếu màn hình trên iPhone hoặc iPad và chọn Duwn Mirror.",
    /* Mirror_Empty_Wired_NoCable   */ L"Kết nối iPhone hoặc iPad với máy tính bằng cáp USB.",
    /* Mirror_Empty_Wired_Preparing */ L"Đang chuẩn bị kết nối USB...",
    /* Mirror_Empty_Wired_Ready     */ L"Sẵn sàng phản chiếu qua USB.",
    /* Mirror_Waiting_Video         */ L"Đang chờ hình ảnh...",
    /* Mirror_WindowsTitle          */ L"CỬA SỔ",
    /* Mirror_Btn_ShowPreview       */ L"Mở xem trước",
    /* Mirror_Btn_HidePreview       */ L"Đóng xem trước",
    /* Mirror_Btn_ShowOutput        */ L"Mở đầu ra",
    /* Mirror_Btn_HideOutput        */ L"Đóng đầu ra",
    /* Mirror_Btn_FullscreenPreview */ L"Xem trước toàn màn hình",
    /* Mirror_Toggle_AlwaysOnTop    */ L"Ghim trên cùng",

    /* Right_DeviceConnection       */ L"KẾT NỐI THIẾT BỊ",
    /* Right_LocalRtpStream         */ L"Luồng RTP/UDP nội bộ",
    /* Right_Btn_Apply              */ L"Áp dụng",
    /* Right_Btn_Eject              */ L"Ngắt kết nối",
    /* Right_Btn_Refresh            */ L"Làm mới",
    /* Right_Signal                 */ L"Tín hiệu",
    /* Right_RealtimeTelemetry      */ L"DỮ LIỆU ĐO TỪ XA TRỰC TIẾP",
    /* Right_Tile_Decoder           */ L"Bộ giải mã",
    /* Right_Tile_RenderFps         */ L"FPS hiển thị",
    /* Right_Tile_QueuePacing       */ L"Điều nhịp hàng đợi",
    /* Right_Tile_AvLag             */ L"Độ trễ AV",
    /* Right_FramesPlural           */ L"Khung hình",
    /* Right_FrameSingular          */ L"Khung hình",
    /* Right_OutputControls         */ L"ĐIỀU KHIỂN ĐẦU RA",
    /* Right_OutputWindowActive     */ L"Ẩn Cửa sổ đầu ra",
    /* Right_ShowOutputWindow       */ L"Hiện Cửa sổ đầu ra",
    /* Right_Btn_Full               */ L"Toàn màn hình",
    /* Right_Btn_Aspect             */ L"Tỷ lệ",
    /* Right_Btn_Pin                */ L"Luôn nổi trên cùng",
    /* Right_Btn_Unmute             */ L"Bật âm",
    /* Right_Btn_Mute               */ L"Tắt âm",
    /* Right_CreatorTipsHeader      */ L"QUAY MÀN HÌNH OBS / TIKTOK LIVE STUDIO",
    /* Right_CreatorTipsDesc        */ L"Thêm Quay Cửa Sổ trong OBS và chọn \"Duwn Mirror Output\" với Windows Graphics Capture (WGC) để phát trực tiếp 60 FPS zero-copy.",

    /* Perf_Title                   */ L"Hiệu suất",
    /* Perf_SourceFps               */ L"FPS nguồn",
    /* Perf_DecodedFps              */ L"FPS giải mã",
    /* Perf_PresentedFps            */ L"FPS hiển thị",
    /* Perf_EncoderFps              */ L"FPS bộ mã hóa",
    /* Perf_SourceRes               */ L"Độ phân giải nguồn",
    /* Perf_CaptureCanvas           */ L"Khung ghi hình",
    /* Perf_PreviewWindow           */ L"Cửa sổ xem trước",
    /* Perf_AudioBuffer             */ L"Bộ đệm âm thanh",
    /* Perf_Underruns               */ L"Thiếu dữ liệu",
    /* Perf_Uptime                  */ L"Thời gian hoạt động",
    /* Perf_DiagnosticsTitle        */ L"Hiệu suất luồng & Chẩn đoán",
    /* Perf_DiagnosticsSub          */ L"Số liệu phần cứng, bộ đệm và hiển thị DXGI thời gian thực",
    /* Perf_FlushPipeline           */ L"Xóa bộ nhớ đệm",
    /* Perf_VideoDecodeRender       */ L"GIẢI MÃ & KẾT XUẤT VIDEO",
    /* Perf_Lbl_RequestedInput      */ L"Đầu vào bộ mã hóa yêu cầu",
    /* Perf_Lbl_ActualSource        */ L"Nguồn hiển thị thực tế",
    /* Perf_Lbl_SourceFps           */ L"FPS nguồn truyền tải",
    /* Perf_Lbl_DecodedPresented    */ L"Đã giải mã / Đã hiển thị",
    /* Perf_Lbl_Decoder             */ L"Bộ giải mã",
    /* Perf_Lbl_QueueDrops          */ L"Hàng đợi / Rơi",
    /* Perf_PresDxgiClock           */ L"HIỂN THỊ & ĐỒNG HỒ DXGI",
    /* Perf_Lbl_Source              */ L"Nguồn",
    /* Perf_Lbl_CaptureCanvas       */ L"Khung ghi hình",
    /* Perf_Lbl_PreviewWindow       */ L"Cửa sổ xem trước",
    /* Perf_Lbl_RendererSurface     */ L"Bộ kết xuất",
    /* Perf_Lbl_ScalerLatency       */ L"Bộ co giãn / Độ trễ",
    /* Perf_AudioWasapiClock        */ L"ÂM THANH & ĐỒNG HỒ WASAPI",
    /* Perf_Lbl_AudioStatus         */ L"Trạng thái âm thanh",
    /* Perf_Lbl_EngineFormat        */ L"Định dạng bộ xử lý: WASAPI 48000 Hz Stereo (Float32)",
    /* Perf_Lbl_AudioClock          */ L"Đồng hồ âm thanh: Đồng hồ lấy mẫu lại liên tục",
    /* Perf_Lbl_AudioMuteState      */ L"Trạng thái tắt âm",
    /* Perf_Lbl_RealUnderruns       */ L"Thiếu dữ liệu thực tế",
    /* Perf_Active                  */ L"Hoạt động",
    /* Perf_MutedSilentBuffer       */ L"Đã tắt âm (Bộ đệm im lặng)",
    /* Perf_UnmutedPlaying          */ L"Bật âm (Đang phát)",
    /* Perf_TransportIpc            */ L"TRUYỀN TẢI AIRPLAY & IPC",
    /* Perf_Lbl_Protocol            */ L"Giao thức AirPlay: RTSP / RTP (Cổng 7000, 7001, 7100)\n",
    /* Perf_Lbl_TransportMode       */ L"Chế độ truyền tải",
    /* Perf_Lbl_SidecarStatus       */ L"Trạng thái Sidecar",
    /* Perf_Lbl_VideoRtpPackets     */ L"Gói tin RTP Video",
    /* Perf_Lbl_AudioRtpPackets     */ L"Gói tin RTP Âm thanh",
    /* Perf_MissingError            */ L"Thiếu / Lỗi",
    /* Perf_ResolutionWarning       */ L"Độ phân giải đầu ra thấp hơn luồng nguồn AirPlay. Chọn Khớp nguồn hoặc chất lượng đầu ra cao hơn.",

    /* Video_Title                  */ L"Video",
    /* Video_Subtitle               */ L"Cấu hình chất lượng thu AirPlay, hiển thị khung hình, kết xuất GPU và chỉnh màu thời gian thực",
    /* Video_QuickSetup             */ L"THIẾT LẬP NHANH",
    /* Video_AirPlayInput           */ L"ĐẦU VÀO AIRPLAY",
    /* Video_ReceiverQuality        */ L"Chất lượng bộ thu",
    /* Video_Requested              */ L"Yêu cầu",
    /* Video_ActualSource           */ L"Nguồn thực tế",
    /* Video_Quality_DeliveredAsRequested */ L"Đạt đúng chất lượng yêu cầu",
    /* Video_Quality_SourceLimited        */ L"Nguồn bị giới hạn bởi thiết bị",
    /* Video_Quality_PartiallyDelivered   */ L"Đạt một phần chất lượng",
    /* Video_PendingReconnect       */ L"Đang chờ kết nối lại để áp dụng cài đặt mới",
    /* Video_SidecarActive          */ L"Bộ thu đang hoạt động",
    /* Video_Delivery                */ L"ĐỘ TRỄ HIỂN THỊ",
    /* Video_DeliveryMode            */ L"Chế độ phát",
    /* Video_Freshness               */ L"Bắt kịp sau",
    /* Video_QueueFrames             */ L"Khung hình chờ",
    /* Video_DeliveryHint            */ L"Áp dụng ngay • Giữ độ phân giải/FPS đã chọn",
    /* Opt_Delivery_Balanced         */ L"Cân bằng",
    /* Opt_Delivery_Balanced_Desc    */ L"Giữ khung hình còn mới; bắt kịp khi bộ đệm bị trễ",
    /* Opt_Delivery_Fastest          */ L"Nhanh nhất",
    /* Opt_Delivery_Fastest_Desc     */ L"Giữ ảnh mới nhất; có thể bỏ khung hình khi dữ liệu đến dồn",
    /* Opt_Delivery_Smooth           */ L"Ưu tiên mượt",
    /* Opt_Delivery_Smooth_Desc      */ L"Giữ tối đa ba khung hình với ngưỡng bắt kịp lớn hơn",
    /* Opt_Delivery_Custom           */ L"Tùy chỉnh",
    /* Opt_Delivery_Custom_Desc      */ L"Chọn số khung chờ và ngưỡng bắt kịp, độc lập với chất lượng",
    /* Video_Output                 */ L"ĐẦU RA",
    /* Video_AutoMatchSource        */ L"Tự động (Trùng khớp nguồn)",
    /* Video_AspectFitBars          */ L"Khớp (Viền đen)",
    /* Video_AspectFillCrop         */ L"Lấp đầy (Cắt viền)",
    /* Video_AspectStretch          */ L"Kéo giãn",
    /* Video_AspectAuto             */ L"Tự động",
    /* Video_CanvasMatchDesc        */ L"Sẵn sàng — Khung hình đầu ra sẽ tự động theo kích thước nguồn mà không có viền đen.",
    /* Video_Rendering              */ L"KẾT XUẤT",
    /* Video_RendererMode           */ L"Chế độ kết xuất",
    /* Video_Resolved               */ L"Đầu ra thực tế",
    /* Video_ZeroCopyActive         */ L"Hoạt động (NV12)",
    /* Video_ZeroCopyDisabled       */ L"Đã tắt",
    /* Video_Color                  */ L"MÀU SẮC",
    /* Video_Live                   */ L"TRỰC TIẾP",
    /* Video_ResetToZeroTooltip     */ L"Nhấp đúp để đặt lại về 0",
    /* Video_ResetTooltip           */ L"Đặt lại về 0",
    /* Video_FilterNotSupported     */ L"Bộ lọc không được bộ kết xuất hỗ trợ",
    /* Video_AdvColorOverview       */ L"TỔNG QUAN MÀU NÂNG CAO & LUỒNG XỬ LÝ",
    /* Video_Collapse               */ L"Thu gọn",
    /* Video_Expand                 */ L"Mở rộng",
    /* Video_ActiveCanvas           */ L"Khung hình hoạt động: {}×{} ({})\n",
    /* Video_AspectBehavior         */ L"Hành vi tỷ lệ: {}\n",
    /* Video_ColorPipeline          */ L"Luồng màu: {}, {}",
    /* Video_Fixed                  */ L"Cố định",
    /* Video_AutoFollowsStream      */ L"Tự động (Theo luồng)",
    /* Video_AutoRange              */ L"Dải màu tự động",
    /* Video_AutoMatrix             */ L"Ma trận tự động",

    /* Opt_Profile_Auto             */ L"Tự động",
    /* Opt_Profile_Auto_Desc        */ L"Cân bằng giữa độ trễ và độ nét hình ảnh",
    /* Opt_Profile_HighQuality      */ L"Chất lượng cao",
    /* Opt_Profile_HighQuality_Desc */ L"Hình ảnh tốt nhất, co giãn bicubic, zero-copy NV12",
    /* Opt_Profile_Balanced         */ L"Cân bằng",
    /* Opt_Profile_Balanced_Desc    */ L"Độ trễ thấp, chuyển ảnh phần cứng tương thích",
    /* Opt_Profile_LowSpec          */ L"Cấu hình thấp",
    /* Opt_Profile_LowSpec_Desc     */ L"Ưu tiên độ phản hồi trên phần cứng yếu",
    /* Opt_Profile_Custom           */ L"Tùy chỉnh",
    /* Opt_Profile_Custom_Desc      */ L"Đang bật ghi đè thủ công",

    /* Opt_Rec_Auto                 */ L"Tự động",
    /* Opt_Rec_Auto_Desc            */ L"Tự động chọn chất lượng tốt nhất và ổn định",
    /* Opt_Rec_720p30               */ L"HD · 30 FPS",
    /* Opt_Rec_720p30_Desc          */ L"Tiết kiệm tài nguyên",
    /* Opt_Rec_720p60               */ L"HD · 60 FPS",
    /* Opt_Rec_720p60_Desc          */ L"Mượt hơn cho chuyển động",
    /* Opt_Rec_1080p30              */ L"Full HD · 30 FPS",
    /* Opt_Rec_1080p30_Desc         */ L"Chất lượng cao",
    /* Opt_Rec_1080p60              */ L"Full HD · 60 FPS",
    /* Opt_Rec_1080p60_Desc         */ L"Chất lượng cao, ưu tiên độ mượt",
    /* Opt_Rec_1440p60              */ L"2K · 60 FPS",
    /* Opt_Rec_1440p60_Desc         */ L"Chất lượng rất cao · Thử nghiệm",
    /* Opt_Rec_Original60           */ L"Gốc · 60 FPS",
    /* Opt_Rec_Original60_Desc      */ L"Truyền nguồn 1:1 ở 60 FPS (không hạ độ phân giải)",

    /* Opt_Out_Auto                 */ L"Tự động",
    /* Opt_Out_Auto_Desc            */ L"Khớp chính xác kích thước luồng nguồn",
    /* Opt_Out_HD                   */ L"HD",
    /* Opt_Out_HD_Desc              */ L"Cạnh dài ~1280 (giữ nguyên tỷ lệ nguồn)",
    /* Opt_Out_FullHD               */ L"Full HD",
    /* Opt_Out_FullHD_Desc          */ L"Cạnh dài ~1920 (giữ nguyên tỷ lệ nguồn)",
    /* Opt_Out_2K                   */ L"2K",
    /* Opt_Out_2K_Desc              */ L"Cạnh dài ~2560 (giữ nguyên tỷ lệ nguồn)",
    /* Opt_Out_4K                   */ L"4K",
    /* Opt_Out_4K_Desc              */ L"Cạnh dài ~3840 (giữ nguyên tỷ lệ nguồn)",
    /* Opt_Out_Original             */ L"Gốc",
    /* Opt_Out_Original_Desc        */ L"Truyền nguồn 1:1 (không hạ độ phân giải)",
    /* Opt_Out_Custom               */ L"Tùy chỉnh…",
    /* Opt_Out_Custom_Desc          */ L"Tùy chỉnh kích thước đầu ra",

    /* Opt_Canvas_FollowSource      */ L"Theo nguồn",
    /* Opt_Canvas_FollowSource_Desc */ L"Tự động theo tỷ lệ nguồn (không viền đen)",
    /* Opt_Canvas_16_9_HD           */ L"16:9 HD",
    /* Opt_Canvas_16_9_HD_Desc      */ L"Khung hình phát sóng 1280×720",
    /* Opt_Canvas_16_9_FullHD       */ L"16:9 Full HD",
    /* Opt_Canvas_16_9_FullHD_Desc  */ L"Khung hình phát sóng 1920×1080",
    /* Opt_Canvas_16_9_2K           */ L"16:9 2K",
    /* Opt_Canvas_16_9_2K_Desc      */ L"Khung hình phát sóng 2560×1440",
    /* Opt_Canvas_Custom            */ L"Tùy chỉnh…",
    /* Opt_Canvas_Custom_Desc       */ L"Khung hình phát sóng tùy chỉnh",

    /* Opt_Aspect_Preserve          */ L"Giữ nguyên",
    /* Opt_Aspect_Preserve_Desc     */ L"Giữ nguyên tỷ lệ nguồn không viền đen hoặc cắt góc",
    /* Opt_Aspect_Auto              */ L"Tự động",
    /* Opt_Aspect_Auto_Desc         */ L"Trùng khớp nguồn trong chế độ Tự động; Khớp trên khung cố định",
    /* Opt_Aspect_Fit               */ L"Khớp (Fit)",
    /* Opt_Aspect_Fit_Desc          */ L"Thêm viền đen; giữ nguyên tỷ lệ khung hình",
    /* Opt_Aspect_Fill              */ L"Lấp đầy (Fill)",
    /* Opt_Aspect_Fill_Desc         */ L"Cắt giữa; lấp đầy toàn bộ khung hình không viền",
    /* Opt_Aspect_Stretch           */ L"Kéo giãn (Stretch)",
    /* Opt_Aspect_Stretch_Desc      */ L"Kéo biến dạng để lấp đầy khung hình không viền",

    /* Opt_Scale_Auto               */ L"Tự động (Khuyên dùng)",
    /* Opt_Scale_Auto_Desc          */ L"Co giãn phần cứng tương thích",
    /* Opt_Scale_Fast               */ L"Nhanh",
    /* Opt_Scale_Fast_Desc          */ L"Tuyến tính / phần cứng gần nhất",
    /* Opt_Scale_Sharp              */ L"Sắc nét",
    /* Opt_Scale_Sharp_Desc         */ L"Song tuyến tính với tăng cường cạnh thích ứng",
    /* Opt_Scale_HighQuality        */ L"Chất lượng cao",
    /* Opt_Scale_HighQuality_Desc   */ L"Bộ lọc bicubic / đa điểm lấy mẫu",

    /* Opt_Pixel_Auto               */ L"Tự động",
    /* Opt_Pixel_Auto_Desc          */ L"Ánh xạ 1:1 pixel khi khớp kích thước, co giãn đơn lẻ khi khác",
    /* Opt_Pixel_On                 */ L"Bật",
    /* Opt_Pixel_On_Desc            */ L"Ánh xạ nguyên 1:1 pixel nghiêm ngặt, căn giữa",
    /* Opt_Pixel_Off                */ L"Tắt",
    /* Opt_Pixel_Off_Desc           */ L"Luôn co giãn để vừa với khung hình đích",

    /* Opt_Rnd_Auto                 */ L"Tự động (Khuyên dùng)",
    /* Opt_Rnd_Auto_Desc            */ L"Chọn luồng phần cứng zero-copy nhanh nhất",
    /* Opt_Rnd_D3D11                */ L"Phần cứng D3D11",
    /* Opt_Rnd_D3D11_Desc           */ L"Bộ xử lý video trực tiếp Zero-Copy (Nhanh nhất)",
    /* Opt_Rnd_Compat               */ L"Tương thích",
    /* Opt_Rnd_Compat_Desc          */ L"Dự phòng Direct3D 11 Blit",
    /* Opt_Rnd_Warp                 */ L"Phần mềm / CPU",
    /* Opt_Rnd_Warp_Desc            */ L"Mô phỏng phần mềm WARP (Tốn CPU)",

    /* Opt_Color_Neutral            */ L"Tự nhiên",
    /* Opt_Color_Neutral_Desc       */ L"Màu luồng tiêu chuẩn không hiệu chỉnh (tất cả về 0)",
    /* Opt_Color_Vivid              */ L"Sống động",
    /* Opt_Color_Vivid_Desc         */ L"Tăng độ nổi bật, độ tương phản và bão hòa cho game",
    /* Opt_Color_Soft               */ L"Dịu mắt",
    /* Opt_Color_Soft_Desc          */ L"Giảm tương phản và bão hòa cho đọc chữ / giao diện",
    /* Opt_Color_Custom             */ L"Tùy chỉnh",
    /* Opt_Color_Custom_Desc        */ L"Tùy chỉnh theo thanh trượt người dùng",

    /* Opt_Range_Auto               */ L"Tự động",
    /* Opt_Range_Auto_Desc          */ L"Theo siêu dữ liệu của luồng",
    /* Opt_Range_Limited            */ L"Giới hạn (16-235)",
    /* Opt_Range_Limited_Desc       */ L"Chuẩn TV 16-235",
    /* Opt_Range_Full               */ L"Toàn dải (0-255)",
    /* Opt_Range_Full_Desc          */ L"Chuẩn PC 0-255",

    /* Opt_Matrix_Auto              */ L"Tự động",
    /* Opt_Matrix_Auto_Desc         */ L"BT.709 cho HD, BT.601 cho SD",
    /* Opt_Matrix_601               */ L"BT.601",
    /* Opt_Matrix_601_Desc          */ L"Chuẩn màu SD / kế thừa",
    /* Opt_Matrix_709               */ L"BT.709",
    /* Opt_Matrix_709_Desc          */ L"Chuẩn màu HD / hiện đại",
    /* Opt_Matrix_2020              */ L"BT.2020",
    /* Opt_Matrix_2020_Desc         */ L"Chuẩn màu UHD / dải màu rộng",

    /* Opt_Lang_System              */ L"Mặc định hệ thống",
    /* Opt_Lang_System_Desc         */ L"Tự động phát hiện English / Tiếng Việt",
    /* Opt_Lang_En                  */ L"English",
    /* Opt_Lang_En_Desc             */ L"English (Hoa Kỳ)",
    /* Opt_Lang_Vi                  */ L"Tiếng Việt",
    /* Opt_Lang_Vi_Desc             */ L"Tiếng Việt (Việt Nam)",

    /* Opt_Audio_SystemDefault      */ L"Mặc định hệ thống",
    /* Opt_Audio_SystemDefault_Desc */ L"Thiết bị kết xuất đa phương tiện mặc định của Windows",
    /* Opt_Audio_DirectEndpoint_Desc*/ L"Thiết bị kết xuất trực tiếp",

    /* Opt_Mon_Primary              */ L"Màn hình chính",
    /* Opt_Mon_Primary_Desc         */ L"Màn hình chính mặc định của Windows",
    /* Opt_Mon_Secondary            */ L"Màn hình phụ",
    /* Opt_Mon_Secondary_Desc       */ L"Màn hình thứ hai (chỉ mục 1)",
    /* Opt_Mon_Current              */ L"Màn hình hiện tại",
    /* Opt_Mon_Current_Desc         */ L"Màn hình nơi cửa sổ chính đang hiển thị",

    /* General_Language             */ L"Ngôn ngữ",
    /* General_Language_System      */ L"Mặc định hệ thống",
    /* General_Language_En          */ L"English",
    /* General_Language_Vi          */ L"Tiếng Việt",
    /* General_StartOnBoot          */ L"Khởi động cùng Windows",
    /* General_StartMinimized       */ L"Khởi động thu nhỏ",
    /* General_AlwaysOnTop          */ L"Luôn hiển thị trên cùng",
    /* General_StartWithWindows     */ L"Khởi động cùng Windows",
    /* General_MinimizeToTray       */ L"Thu nhỏ xuống khay hệ thống",
    /* General_RememberWindowPos    */ L"Ghi nhớ vị trí cửa sổ",
    /* General_AllowPublicNetworks  */ L"Cho phép AirPlay trên mạng công cộng",
    /* Network_PublicWarning        */ L"Mạng hiện tại đang là mạng Công cộng. Windows Firewall có thể chặn kết nối AirPlay.",
    /* Network_OpenNetworkSettings  */ L"Mở cài đặt mạng",
    /* Network_AllowOnThisNetwork   */ L"Cho phép trên mạng này",
    /* Network_PublicSecurityTitle  */ L"AirPlay Mạng Công cộng — Cảnh báo Bảo mật",
    /* Network_PublicSecurityPrompt */ L"Bật AirPlay trên mạng công cộng sẽ cho phép kết nối đến từ mọi thiết bị trên mạng không tin cậy này (ví dụ: Wi-Fi quán cà phê, khách sạn, sân bay).\n\nThao tác này yêu cầu quyền quản trị viên (UAC) để thiết lập Windows Defender Firewall cho duwn-mirror.exe và uxplay.exe.\n\nBạn có muốn tiếp tục không?",
    /* Network_PublicUacDenied          */ L"Quyền quản trị viên bị từ chối hoặc không thể tạo quy tắc tường lửa. AirPlay vẫn bị tắt trên mạng công cộng.",
    /* Network_PublicDisableUacDenied   */ L"Cần quyền quản trị viên để xóa các quy tắc tường lửa cho mạng Công cộng.",
    /* Network_PublicMismatchWarning    */ L"Các quy tắc tường lửa cho mạng Công cộng hiện đang được bật trong Windows Defender Firewall.",
    /* Network_PublicRulesMissingWarning*/ L"Cài đặt đã bật mạng công cộng, nhưng thiếu quy tắc trong Windows Firewall. AirPlay trên mạng công cộng đã được tắt để bảo mật.",
    /* Network_RepairPublicRules        */ L"Sửa quy tắc tường lửa",
    /* Network_DisablePublicRules       */ L"Tắt quy tắc công cộng",

    /* Output_Resolution            */ L"Độ phân giải",
    /* Output_Quality               */ L"Chất lượng đầu ra",
    /* Output_CaptureCanvas         */ L"Khung hình phát sóng",
    /* Output_AspectMode            */ L"Chế độ tỷ lệ",
    /* Output_ScalingQuality        */ L"Chất lượng co giãn",
    /* Output_PixelPerfect          */ L"Pixel hoàn hảo",
    /* Output_Renderer              */ L"Bộ kết xuất",
    /* Output_Profile               */ L"Cấu hình",
    /* Output_ColorPreset           */ L"Cài đặt màu",
    /* Output_Brightness            */ L"Độ sáng",
    /* Output_Contrast              */ L"Độ tương phản",
    /* Output_Saturation            */ L"Độ bão hòa",
    /* Output_Hue                   */ L"Sắc thái",
    /* Output_Sharpness             */ L"Độ sắc nét",
    /* Output_ColorRange            */ L"Dải màu",
    /* Output_ColorMatrix           */ L"Ma trận màu",
    /* Output_Reset                 */ L"Đặt lại mặc định",
    /* Output_AutoOpenOutputWindow  */ L"Tự động mở Cửa sổ đầu ra",
    /* Output_StartFullscreen       */ L"Khởi động toàn màn hình",
    /* Output_PreferredMonitor      */ L"Màn hình ưu tiên",
    /* Output_HideCursor            */ L"Ẩn con trỏ chuột trên video",
    /* Output_RememberOutputPos     */ L"Ghi nhớ vị trí Cửa sổ đầu ra",

    /* Audio_OutputDevice           */ L"Thiết bị đầu ra",
    /* Audio_SystemDefault          */ L"Mặc định hệ thống",
    /* Audio_Mute                   */ L"Tắt âm thanh",
    /* Audio_Volume                 */ L"Âm lượng",
    /* Audio_SyncOffset             */ L"Độ trễ đồng bộ (ms)",
    /* Audio_TestButton             */ L"Kiểm tra âm thanh",
    /* Audio_Diagnostics            */ L"Chẩn đoán",
    /* Audio_SessionName            */ L"Tên phiên",
    /* Audio_BufferMs               */ L"Bộ đệm",
    /* Audio_Underruns              */ L"Thiếu dữ liệu",
    /* Audio_SessionNameLbl         */ L"Tên phiên:",
    /* Audio_FormatLbl              */ L"Định dạng:",
    /* Audio_FormatVal              */ L"48 kHz Stereo Float32 (WASAPI Chia sẻ)",
    /* Audio_BufferLbl              */ L"Bộ đệm:",
    /* Audio_UnderrunsLbl           */ L"Thiếu dữ liệu:",
    /* Audio_DeviceLbl              */ L"Thiết bị:",
    /* Audio_PlayTestTone           */ L"Phát âm thanh kiểm tra",

    /* Privacy_Title                */ L"Riêng tư & Pháp lý",
    /* Privacy_OpenSource           */ L"Phần mềm mã nguồn mở",
    /* Privacy_ThirdParty           */ L"Thông báo bên thứ ba",
    /* Privacy_License              */ L"Giấy phép",
    /* Privacy_NoTelemetry          */ L"Không thu thập dữ liệu đo từ xa hoặc phân tích.",
    /* Privacy_NoDataExternal       */ L"Không có dữ liệu nào được truyền tới máy chủ bên ngoài.",
    /* Privacy_OpenSourceDesc       */ L"Duwn Mirror là phần mềm mã nguồn mở. Mã nguồn có tại:",
    /* Privacy_ThirdPartyComponents */ L"Các thành phần bên thứ ba: GStreamer (LGPL 2.1+), UxPlay (GPL 3.0),",
    /* Privacy_ThirdPartyMore       */ L"libplist (LGPL 2.1), OpenSSL (Apache 2.0), và các thư viện khác.",
    /* Privacy_SeeNotices           */ L"Xem tệp THIRD_PARTY_NOTICES.txt trong thư mục cài đặt.",

    /* Adv_Title                    */ L"Nâng cao",
    /* Adv_DebugLog                 */ L"Ghi nhật ký gỡ lỗi",
    /* Adv_FlushPipeline            */ L"Xóa bộ nhớ đệm",
    /* Adv_Renderer                 */ L"Bộ kết xuất",
    /* Adv_Profile                  */ L"Cấu hình hiệu suất",

    /* About_VersionTitle           */ L"Phiên bản 1.0.0 (Xem trước kết nối hai chế độ)",
    /* About_Title                  */ L"Về Duwn Mirror",
    /* About_Desc                   */ L"Phản chiếu màn hình không dây AirPlay & USB có dây cho Windows",
    /* About_Copyright              */ L"Bản quyền © 2026 Nhóm phát triển Duwn Mirror",
    /* About_Btn_CopyDiag           */ L"Sao chép chẩn đoán",
    /* About_Btn_OpenLogs           */ L"Mở thư mục nhật ký",
    /* About_Btn_Notices            */ L"Thông báo bên thứ ba",
    /* About_Btn_GitHub             */ L"GitHub",
    /* About_DiagCopied             */ L"Đã sao chép vào khay nhớ tạm!",
    /* About_OpenSourceSummary      */ L"Duwn Mirror được xây dựng bằng phần mềm mã nguồn mở bao gồm UxPlay (GPLv3), GStreamer (LGPL), libplist, OpenSSL và nlohmann/json.",
    /* About_SpecLead               */ L"Duwn Mirror hỗ trợ phản chiếu không dây AirPlay và nhận diện thiết bị USB trên Windows.\n\n",
    /* About_SpecUi                 */ L"• Giao diện: Bề mặt điều khiển tăng tốc phần cứng Direct2D & DirectWrite (tách biệt).\n",
    /* About_SpecVideo              */ L"• Luồng video: Giải mã phần cứng D3D11 NV12 qua Microsoft Media Foundation.\n",
    /* About_SpecPres               */ L"• Hiển thị: Chuỗi hoán đổi DXGI Flip-Discard với điều nhịp hiển thị Present0 độ trễ thấp.\n",
    /* About_SpecAudio              */ L"• Bộ xử lý âm thanh: Windows Audio Session API (WASAPI) với đồng hồ phát liên tục.\n",
    /* About_SpecCapture            */ L"• Quay phát sóng: OutputWindow chuyên dụng sạch sẽ tối ưu cho OBS Studio và TikTok Live Studio.",
    /* About_Footer                 */ L"Duwn Mirror • Phản chiếu không dây AirPlay & USB có dây",

    /* FirstRun_Title               */ L"Chào mừng đến với Duwn Mirror",
    /* FirstRun_Desc                */ L"Phản chiếu màn hình siêu nhanh cho iPhone và iPad trên Windows.",
    /* FirstRun_AirPlay_Title       */ L"Không dây AirPlay",
    /* FirstRun_AirPlay_Desc        */ L"Phản chiếu ngay lập tức qua Wi-Fi không cần dây cáp. Tiện lợi cho trình chiếu và giải trí.",
    /* FirstRun_Wired_Title         */ L"USB có dây",
    /* FirstRun_Wired_Desc          */ L"Kết nối qua cáp USB Apple với độ trễ cực thấp. Lý tưởng cho phát trực tiếp và chơi game.",
    /* FirstRun_Btn_Continue        */ L"Bắt đầu ngay",

    /* Crash_Banner_Text            */ L"Duwn Mirror đã đóng bất ngờ trong lần chạy trước.",
    /* Crash_Banner_OpenLogs        */ L"Mở nhật ký",
    /* Crash_Banner_Dismiss         */ L"Bỏ qua",

    /* Common_Save                  */ L"Lưu",
    /* Common_Reset                 */ L"Đặt lại",
    /* Common_Cancel                */ L"Hủy",
    /* Common_Apply                 */ L"Áp dụng",
    /* Common_On                    */ L"Bật",
    /* Common_Off                   */ L"Tắt",
    /* Common_Auto                  */ L"Tự động",
    /* Common_Custom                */ L"Tùy chỉnh",
    /* Common_Default               */ L"Mặc định",
    /* Common_Test                  */ L"Kiểm tra",
    L"Âm thanh", L"CHẾ ĐỘ KẾT NỐI", L"Kết nối không dây AirPlay", L"Kết nối USB có dây",
    L"Kết nối bằng tính năng Phản chiếu màn hình trên iPhone qua Wi-Fi",
    L"KẾT NỐI TRONG BA BƯỚC",
    L"1. Kết nối iPhone và PC vào cùng một mạng",
    L"2. Mở Phản chiếu màn hình trên iPhone",
    L"3. Chọn Duwn Mirror",
    L"Khởi động lại dịch vụ AirPlay",
    L"Phản chiếu qua kết nối USB của Apple",
    L"KẾT NỐI CÓ DÂY", L"Chưa có thiết bị USB nào được kết nối", L"Đã nhận diện thiết bị Apple",
    L"Thiếu hỗ trợ Apple Mobile Device. Hãy cài Apple Devices cho Windows.",
    L"Dịch vụ Apple Mobile Device đã dừng. Hãy khởi động dịch vụ và kết nối lại.",
    L"Bật Điểm truy cập cá nhân trên iPhone để kích hoạt kết nối mạng qua USB.",
    L"Chưa thể xác minh tin cậy khi thiếu cầu nối thiết bị Apple",
    L"Giao diện USB", L"Môi trường Apple", L"Tin cậy", L"Phiên", L"Kiểu máy", L"Phiên bản iOS",
    L"Pin", L"Tốc độ USB", L"Chưa có thông tin",
    L"KẾT NỐI BẰNG CÁP", L"1. Kết nối iPhone hoặc iPad bằng cáp USB",
    L"2. Mở khóa thiết bị", L"3. Chọn Tin cậy máy tính này nếu được hỏi",
    L"4. Chọn Duwn Mirror trong Phản chiếu màn hình",
    L"Làm mới thiết bị USB", L"Kiểm tra kết nối USB", L"Mở Trình quản lý Thiết bị",
    L"Đang chuẩn bị kết nối USB...", L"Chế độ có dây chỉ dùng mạng USB của Apple",
    L"Cáp", L"Thiết bị", L"Dịch vụ đang chạy", L"Dịch vụ đã dừng", L"Chưa cài đặt", L"Đang quét thiết bị USB…",
    L"Đang phát qua", L"Thiết bị âm thanh đã chọn không khả dụng; thiết bị trước vẫn hoạt động.",
    L"Ghi nhớ chế độ kết nối đã chọn", L"Chế độ kết nối mặc định", L"Mở thư mục nhật ký", L"Mở tệp cài đặt",
    L"THIẾT BỊ PHÁT", L"TRẠNG THÁI ÂM THANH", L"KHẮC PHỤC SỰ CỐ",
    L"Âm lượng phát theo thiết bị đầu ra Windows đã chọn. Tắt tiếng ở đây chỉ áp dụng cho Duwn Mirror.",

    /* Wired_DeviceControl           */ L"Điều khiển thiết bị",
    /* Wired_ControlActive          */ L"Đang điều khiển thiết bị",
    /* Wired_ControlReady           */ L"Sẵn sàng điều khiển",
    /* Wired_ControlStarting        */ L"Đang khởi động cầu nối…",
    /* Wired_ControlConnectingRsd   */ L"Đang kết nối đường hầm RSD…",
    /* Wired_ControlOpeningHid      */ L"Đang mở dịch vụ HID…",
    /* Wired_ControlError           */ L"Lỗi điều khiển",
    /* Wired_ControlDisabled        */ L"Đã tắt điều khiển",
    /* Wired_ControlConnectedNoVideo*/ L"Đã kết nối điều khiển — chưa có hình ảnh",
    /* Wired_BtnHome                */ L"Màn hình chính",
    /* Wired_BtnLock                */ L"Nguồn",
    /* Wired_BtnVolDown             */ L"Giảm âm",
    /* Wired_BtnVolUp               */ L"Tăng âm",
    /* Wired_BtnMute                */ L"Tắt tiếng",
    /* Wired_BtnSiri                */ L"Siri",
    /* Wired_DisableControl         */ L"Tắt điều khiển",
    /* Wired_EnableControl          */ L"Bật điều khiển",
    /* Wired_ScreenMirroring        */ L"Phản chiếu màn hình",
    /* Wired_WaitingVideoStream     */ L"Đang chờ luồng hình ảnh…",
    /* Wired_ShortcutsHint          */ L"Phím tắt: Ctrl+H Home • Ctrl+L Khóa • Ctrl+[ Giảm âm • Ctrl+] Tăng âm • Ctrl+S Siri",
    /* Wired_LatencyTelemetry       */ L"Sự kiện: {} | Độ trễ P50: {:.1f}ms | P95: {:.1f}ms | TB: {:.1f}ms",
    /* Wired_PreparingUsbNetwork    */ L"Đang chuẩn bị kết nối USB...",
    /* Wired_EnablePersonalHotspot  */ L"Bật Điểm truy cập cá nhân trên iPhone để kích hoạt kết nối mạng qua USB.",
    /* Wired_ReconnectMirroring     */ L"Nếu màn hình vẫn đen, hãy tắt rồi kết nối lại Phản chiếu màn hình trên iPhone.",
    /* Video_HevcUnavailable        */ L"Chưa cài đặt tiện ích mở rộng HEVC Video trên Windows. Vui lòng cài đặt HEVC Video Extensions từ Microsoft Store để hỗ trợ H.265.",
    /* Wired_RoutingFailure         */ L"Mất kết nối có dây hoặc ngắt chia sẻ mạng USB. Vui lòng kiểm tra cáp USB và Điểm truy cập cá nhân.",
    /* Video_DecoderInitFailure     */ L"Không thể khởi tạo bộ giải mã video phần cứng cho định dạng luồng.",
    /* Nav_Color                    */ L"Màu sắc",
    /* Nav_Diagnostics              */ L"Chẩn đoán",
    /* Common_ScreenOnly            */ L"Chỉ màn hình",
    /* Common_BackToWorkspace       */ L"Về Workspace",
    /* Common_QuickVolume           */ L"Âm lượng nhanh",
    /* Mirror_Toggle_OutputToolbar  */ L"Hiện thanh công cụ trên cửa sổ xuất",
    /* Mirror_Btn_DisconnectSession */ L"Ngắt kết nối",
    /* Mirror_Btn_DisconnectDisabledTooltip */ L"Chưa có thiết bị kết nối",
    /* Output_WaitingForFrame       */ L"Đang chờ hình ảnh…",
    /* Output_Fit                   */ L"Vừa",
    /* Output_AlwaysOnTop           */ L"Ghim",
    /* Output_Fullscreen           */ L"Toàn màn",
    /* Output_Mute                  */ L"Tắt tiếng",
    /* Output_Unmute                */ L"Bật tiếng",
};

static_assert(static_cast<size_t>(S::_COUNT) == std::size(kEn),
    "kEn table size mismatch — add missing strings");
static_assert(static_cast<size_t>(S::_COUNT) == std::size(kVi),
    "kVi table size mismatch — add missing strings");

// ---------------------------------------------------------------------------
// Runtime state
// ---------------------------------------------------------------------------
static Lang s_lang = Lang::System;
static const wchar_t* const* s_table = kEn; // pointer to active table

static Lang ResolveSystem() noexcept {
    LANGID lcid = ::GetUserDefaultUILanguage();
    WORD primary = PRIMARYLANGID(lcid);
    if (primary == LANG_VIETNAMESE) return Lang::Vi;
    return Lang::En;
}

void SetLang(Lang lang) noexcept {
    Lang resolved = (lang == Lang::System) ? ResolveSystem() : lang;
    s_lang = resolved;
    s_table = (resolved == Lang::Vi) ? kVi : kEn;
}

Lang CurrentLang() noexcept {
    return s_lang;
}

const wchar_t* Get(S id) noexcept {
    auto idx = static_cast<size_t>(id);
    if (idx >= static_cast<size_t>(S::_COUNT)) return L"???";
    return s_table[idx];
}

} // namespace duwn::ui::loc
