#pragma once
// Version.h — Centralized build and product version information.
// Automatically generated by CMake from src/common/Version.h.in.
// DO NOT EDIT DIRECTLY.

#define DUWN_PRODUCT_NAME        "Duwn Mirror"
#define DUWN_PRODUCT_NAME_W      L"Duwn Mirror"
#define DUWN_VERSION_MAJOR       1
#define DUWN_VERSION_MINOR       1
#define DUWN_VERSION_PATCH       3
#define DUWN_VERSION_STRING      "1.1.3"
#define DUWN_VERSION_STRING_W    L"1.1.3"
#define DUWN_GIT_COMMIT_HASH     "c2c5e40cb25a7bdeb131ba781dbc16b78b7c9e41"
#define DUWN_GIT_COMMIT_SHORT    "c2c5e40"
#define DUWN_GIT_BRANCH          "main"
#define DUWN_GIT_IS_DIRTY        1
#define DUWN_BUILD_TIMESTAMP     "2026-10-07 09:05:51 UTC"
#define DUWN_BUILD_TIMESTAMP_W   L"2026-10-07 09:05:51 UTC"
#define DUWN_BUILD_PLATFORM      "x64"
#define DUWN_BUILD_PLATFORM_W    L"x64"
#define DUWN_COPYRIGHT_W         L"Copyright (c) 2026 Duwn Mirror Contributors"
