#pragma once
// Version.h — Centralized build and product version information.
// Automatically generated by CMake from src/common/Version.h.in.
// DO NOT EDIT DIRECTLY.

#define DUWN_PRODUCT_NAME        "Duwn Mirror"
#define DUWN_PRODUCT_NAME_W      L"Duwn Mirror"
#define DUWN_VERSION_MAJOR       1
#define DUWN_VERSION_MINOR       1
#define DUWN_VERSION_PATCH       2
#define DUWN_VERSION_STRING      "1.1.2"
#define DUWN_VERSION_STRING_W    L"1.1.2"
#define DUWN_GIT_COMMIT_HASH     "6c1aaa614aebcc33094f61e3845d8230495919ad"
#define DUWN_GIT_COMMIT_SHORT    "6c1aaa6"
#define DUWN_GIT_BRANCH          "main"
#define DUWN_GIT_IS_DIRTY        1
#define DUWN_BUILD_TIMESTAMP     "2026-10-06 09:55:12 UTC"
#define DUWN_BUILD_TIMESTAMP_W   L"2026-10-06 09:55:12 UTC"
#define DUWN_BUILD_PLATFORM      "x64"
#define DUWN_BUILD_PLATFORM_W    L"x64"
#define DUWN_COPYRIGHT_W         L"Copyright (c) 2026 Duwn Mirror Contributors"
